### ISSUE TITLE
Integer underflow in EatHook::hook

### ISSUE THREAD

**Issue by denzo9** [stevemk14ebr/PolyHook_2_0#105]
On x86 machines, the case where `m_fnCallback < m_moduleBase` causes an integer underflow that leads to an unnecessary allocation of a trampoline. 

https://github.com/stevemk14ebr/PolyHook_2_0/blob/64ca107a93b988cd1a1d118283fbf134fd82a0bd/sources/EatHook.cpp#L24

**Comment by stevemk14ebr** [comment]
I'll merge when you do, thanks!
