### ISSUE TITLE
Reference member variable in Detour

### ISSUE THREAD

**Issue by denzo9** [stevemk14ebr/PolyHook_2_0#107]
Is there a reason to have `m_disasm` as an `ADisassembler&`, instead of a smart pointer? This will prevent any potential lifetime issues.

**Comment by stevemk14ebr** [comment]
This was chosen to allow the disassembler to be initialized on that stack, and for the parent class that holds m_disasm to not need to use smart pointers (or heap allocation generally), which introduces an extra nullable state

**Comment by denzo9** [comment]
Why is using smart pointers an issue for the parent class? The case of accessing a pointer to invalid memory seems more dangerous and pretty likely to occur in this context

**Comment by stevemk14ebr** [comment]
It's not particularly an issue just an interface choice. I wanted to allow construction on the stack, and most ways you use hooks you'd want the disassembler to be alive as long as the hook instance is so it made sense. Adding in smart pointers or just allocation generally would have been additional complexity and introduce a nullable state I didn't want to handle. So I made it a requirement of the interface the passed dissassembler be alive as long as the class is
