### ISSUE TITLE
Helper function for creating hardware breakpoints

### ISSUE THREAD

**Issue by pitoriex** [stevemk14ebr/PolyHook_2_0#109]
Hello, I was wondering if there are any plans to add a helper function that registers a hardware breakpoint on all threads at once in the current process. The current way a hardware breakpoint is created with the thread handle parameter looks more like a library-internal function than one that should be used by the end user.

Like, what would be the suggested way of using it? Using CreateToolhelp32Snapshot, Thread32First and Thread32Next to iterate all threads and create a `PLH::HWBreakPointHook` for each thread? That doesn't sound very end user friendly.

Thanks for any thoughts!

**Comment by stevemk14ebr** [comment]
It was intentionally done this way to give the user freedom to choose how they want to get a handle. There are other ways that just toolhelp to get a handle, and sometimes you might already have one. If you want to contribute a PR to add a new contructor that enumerates all threads, except the current thread, and sets the hook on each you may do that and I would review it, but I will not implement this myself.
