### ISSUE TITLE
Is this RVA2VA needed?

### ISSUE THREAD

**Issue by zolcsieles** [stevemk14ebr/PolyHook_2_0#11]
I don't know, but the next RVA2VA looks unnecessary.

https://github.com/stevemk14ebr/PolyHook_2_0/blob/8f8ad1525e5e94f38c98434c764bdf901adc4d61/sources/EatHook.cpp#L150

**Comment by stevemk14ebr** [comment]
yea it's unnecessary, if you submit a pr ill merge
