### ISSUE TITLE
 Visual Studio 2022 build

### ISSUE THREAD

**Issue by pp9999** [stevemk14ebr/PolyHook_2_0#110]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:\Users\Alar\PolyHook_2_0\CMakeLists.txt:3 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.	PolyHook_2	C:\Users\Alar\PolyHook_2_0\CMakeLists.txt	3	
```
How does one fix this? trying to build it on  Visual Studio 2022

**Comment by pp9999** [comment]
After lot digging, err something somewhere is outdated. Trying to edit CmakeSettings.json Gives options up to VS 16 2019 win64.
![cmake11](https://user-images.githubusercontent.com/38459022/148987986-52929690-7d08-429d-800b-30ff5611575e.png)
But I wanted to edit it to VS 17 2022.

After digging some more I found this thread :https://stackoverflow.com/questions/60068168/cmake-problem-could-not-find-any-instance-of-visual-studio
Made my own go with it.
![cmake22](https://user-images.githubusercontent.com/38459022/148988701-ad5ab7cb-9fbd-449e-a8e8-48b053914ddf.png)
It worked build folder was made with ALL_BUILD.vcxproj and other stuff.

**Comment by stevemk14ebr** [comment]
You just need to add proper entries here, they're made manually. The drop down list shows whatever is put here:

 https://github.com/stevemk14ebr/PolyHook_2_0/blob/master/CMakeSettings.json
