### ISSUE TITLE
EAT Hook using absolute module path or module handle?

### ISSUE THREAD

**Issue by acidicoala** [stevemk14ebr/PolyHook_2_0#114]
Good day.

Would it be possible to add support for absolute module paths or better yet, module handles, for the `EatHook` class? This is needed for cases where a target process loads the same DLL multiple times from different paths.

**Comment by stevemk14ebr** [comment]
Absolutely! If you're up for it I would review a PR if you're willing to work on this. Thanks for your interest.

**Comment by acidicoala** [comment]
Closing this, since it has been implemented in #115.

P.S. There is a question pending regarding API consistency https://github.com/stevemk14ebr/PolyHook_2_0/pull/115#issuecomment-1039558292.
