### ISSUE TITLE
Relocate IP Relative Data Instructions

### ISSUE THREAD

**Issue by acidicoala** [stevemk14ebr/PolyHook_2_0#119]
Good day. I'm facing a "Cannot fixup IP relative data operation, needed disp. beyond max disp range" error and trying to think about potential solutions. In my case, the function that needs to be hook indeed has a tiny body:

![tiny](https://user-images.githubusercontent.com/67734819/155900955-019faebf-26c2-459c-85fa-466710273b5b.jpg)

This got me thinking: what if we copied the entire function body to the trampoline? This surely would affect instructions with relative addressing mode, but this can be adjusted like it is done in other places by polyhook. Does this approach stand a chance? Even if it doesn't guarantee 100% success rate, perhaps it would still be able to solve simpler cases like in the above screenshot?

**Comment by stevemk14ebr** [comment]
so this case isn't handled because it actually requires instruction re-writing. All the other replacement forms can be fixed by modifying displacements/immediates or indirecting through the jump table. The instructions and their widths stay constant. For data operations like your compare here where the address is relative to the IP have to be re-written with a totally new instruction sequence that can perform the same semantic operation, but with different instructions that can encode the new, much much larger, displacements. This is _SUPER_ hard to get right generally, and may even require a symbolic analysis engine. 

Copying the entire function to the trampoline wouldn't fix this. In face us needing a trampoline at all is the source of the problem! Because I don't have fine grained control over how far away the trampoline is from the original function, the more and more functions you hook, the more and more likely it is you get a bad trampoline allocation that too far away and a data operation fixup like this errors out. To fix this I gave the user control of the trampline allocation via some flags, but this need to be manually fixed by the user via byte-patching on a case by case basis.

**Comment by stevemk14ebr** [comment]
This could perhaps be fixed with a 'rewrite map' or something simpler than a symbolic engine that is designed to handle only the very common instructions such as cmp here. The rewrite map would then have an entry that says 'if you see cmp' replace with these generic instructions 'X, Y, Z' that can do that compare, but are not limited by their placement. This is more brittle, but would work, and the trampoline is large enough the replacement instruction size wouldn't be of much concern. 

This is a long term goal to handle this. I just haven't gotten there yet, and am focusing on other project recently. Perhaps I will fix eventually, maybe.

**Comment by acidicoala** [comment]
I can't say that I fully grasp the issue, so allow me to ask further questions.

> This is SUPER hard to get right generally

I understand why it's hard when you have to maintain the instruction length. But since in trampoline we are not restricted to size, what are the challenges? Is it because with larger instructions not only we have to adjust relative offsets with respect to trampoline location, but also take into account the local offsets that have been introduced due to increased instruction sizes?

> Copying the entire function to the trampoline wouldn't fix this. In face us needing a trampoline at all is the source of the problem!

Do I understand correctly that the true nature of the problem is that some functions are so small, that we cannot even generate a jump to trampoline?

> The rewrite map would then have an entry that says 'if you see cmp' replace with these generic instructions 'X, Y, Z' that can do that compare, but are not limited by their placement.

Does that mean this re-write map would have to have rules to handle all instructions that have relative addressing mode?

**Comment by stevemk14ebr** [comment]
> I understand why it's hard when you have to maintain the instruction length. But since in trampoline we are not restricted to size, what are the challenges? Is it because with larger instructions not only we have to adjust relative offsets with respect to trampoline location, but also take into account the local offsets that have been introduced due to increased instruction sizes?

Correct, this is a major challenge. Relocating the instructions is fairly complex already, doing this with also messing with instruction lengths obviously complicates that. It's not the _primary_ challenge here though. I'm most concerned with maintaining the original meaning of the program while replacing instructions. As I mentioned earlier some sort of 'translation' or 'replacement' map would be required, to replace position dependant data operations with position independant equivalents. Enumerating these cases, determining if that set is finite, then writing the stubs to generate these snippets would take some time and be a bit of a challenge. Solvable, but work. Not sure about how general it'd be, but it would probably work on non-obfuscated programs generated by one of the major modern compilers.

> Do I understand correctly that the true nature of the problem is that some functions are so small, that we cannot even generate a jump to trampoline?

In general this is true, but it is a separate issue from the one on hand. What I meant by the trampoline being the source of the problem, is that by it existing we are required to copy some small part of the function prologue and re-locate it to the trampoline. This relocation problem is what causes the harder knock on issues with some instructions being moved to far, at which point relocation is impossible, as per your original post about the warning. This is when instruction substitution is required, and as I say above is complex. If there was a world where trampolines didn't have to exist, hooking would be easy as heck :). That's an imaginary world though ahah.

> Does that mean this re-write map would have to have rules to handle all instructions that have relative addressing mode?
Actually no, cool enough. The jump table I use severely mitigates this issue, and is why relocation in Polyhook works better than other libraries. All control flow operations such as jmp, conditions jmps, calls, etc can be pointed at a jump table entry if they're moved too far and relocation becomes impossible. This is due to the jump table being at the end of the trampoline itself, it's always right next to and in close range of these moved instructions. Data operations break this though, because they cannot be just pointed through and intermediate jmp table entry. So only ip relative data operations like mov rax, [rip+mem], cmp rax, [rip+mem], etc would need to be encoded in this table.

**Comment by stevemk14ebr** [comment]
I will work on this eventually, the best way to help with this is to post any other prologues that cause this error. This will help research which instructions are common and could use replacement entries. Once we have a few of these, I can work on an implementation.

**Comment by acidicoala** [comment]
> This relocation problem is what causes the harder knock on issues with some instructions being moved to far, at which point relocation is impossible

OK. So, for example, let's say we have an IP relative instruction in function prologue that can encode +- 256 bytes offset. But the trampoline was allocated farther than max offset, say 300 bytes afar. Hence, that IP relative instruction cannot fit the full offset length. Did I understand the problem correctly this time? And do I understand correctly that the solution you envision involves replacing those instructions with semantically identical ones that don't use relative addressing mode? Wouldn't they also be potentially larger?


Also, what if we split trampoline into 2 or more smaller parts that could be fit into code caves that are closer to the IP relative instructions, unlike the full trampoline. Does this have any potential?

> the best way to help with this is to post any other prologues that cause this error

Sounds like a plan. Should we open an open-ended issue where people could post examples of function prologues that couldn't be hooked?

**Comment by stevemk14ebr** [comment]
> Did I understand the problem correctly this time? And do I understand correctly that the solution you envision involves replacing those instructions with semantically identical ones that don't use relative addressing mode? Wouldn't they also be potentially larger?

Yup you got it. And yes they could be larger, probably larger, I can't think of a case it'd be smaller unless we replaced an operation with a short jmp to a cave like you suggest later. And yes that could be a way to do this, but I think I'd rather insert a few larger instructions instead for performance to avoid branching.

> Should we open an open-ended issue where people could post examples of function prologues that couldn't be hooked?

That would be really great! Go for it

**Comment by acidicoala** [comment]
Ok, couple of new points. In the example given in the OP, I think the `cmp` instruction is fine, it uses *DISPLACEMENT* operand (i.e. absolute address). The real troublemaker here is the `jmp` short instruction which is limited to `[-128, +127]` byte range, if I understand correctly.

In general, a brief search through the x86 instruction reference (for example [here](http://ref.x86asm.net/coder64-abc.html)) reveals that only 3 family of instructions make use of the relative addressing mode (`rel8` and `rel16/32` operands). Those are `call`, `loop`, and a family of jump instructions. Converting the `call` and `jmp` instructions to position-independent variants seems like a trivial task. I have no idea how `loop` & [jcc](https://www.felixcloutier.com/x86/jcc) family can be handled, as they offer no addressing mode other than relative to IP. Do you have a plan for those?

---

Also, how does polyhook handle cases where there is an IP-relative instruction, following the `jmp` to hooked function instruction, which points to an instruction that was replaced by the `jmp` to hooked function?

E.g. Before hook:
```
     mov eax, 0
 --> inc eax
|    cmp eax, 5
 --  jne -3 (3 instructions in this pseudo-notation)
```
After hook (not taking into account actual instruction sizes) :

```
     jmp program.hook_func
     nop  // Padding for alignment
 --> nop  // Padding for alignment
|    nop  // Padding for alignment
|    cmp eax, 5
 --  jne -3
```
Won't it be pointing to a "dangling" instruction?

**Comment by acidicoala** [comment]
Actually I can already see solutions for cases like `JECXZ`. It can be replaced with
```
test ecx
je ptr_to_absolute_address
```

So the main challenge that remains is correcting the offsets if instruction sizes have changed?

**Comment by acidicoala** [comment]
> 1. Identify instructions worth putting in replacement map

There aren't that many instructions that make use of relative addressing mode on first glance. 1 `call` instruction, 4 `loop` instructions, and about 20-30 `jmp`/`jcc` variants. I can list them in a new issue alongside potential replacements.

**Comment by stevemk14ebr** [comment]
That would be awesome! Your list is missing some though, immediately obvious is the cmp like here, and lea too probably

**Comment by acidicoala** [comment]
Yes, of course. But the thing is, I want to derive a general rule that would cover all cases that need to be addressed. Please do correct me if I got something wrong, but here is my understanding so far:

1. In x86 there is no straightforward EIP-relative addressing, apart from the control flow instructions (call, jmp, loop). They all have absolute/indirect addressing mode alternatives and all use distinct opcodes, which makes it easier to replace them.
1. In x86-64, in addition to the above-mentioned control flow instructions, RIP-relative addressing mode is quite common and is achieved **if and only if** the *ModR/M* byte contains `MOD=00` **AND** `RM=101` (as can be seen in [this table](https://wiki.osdev.org/X86-64_Instruction_Encoding#32.2F64-bit_addressing)). Since instructions with different addressing modes share same opcode, we should be checking the ModRM byte, rather than specific instructions like `cmp`. i.e.:
  ```cpp
  enum { // bit masks
    MOD = 0b11000000,
    REG = 0b00111000,
    RM  = 0b00000111
  };

  BYTE mod_rm = extract_mod_rm(instruction);
  
  bool is_mod_00 = (mod_rm & MOD) == 0b00000000;
  bool is_rm_101 = (mod_rm & RM ) == 0b00000101;
  bool is_rip_relative = is_mod_00 && is_rm_101;
  ```

Did I miss anything?

**Comment by stevemk14ebr** [comment]
Yes that's correct you understand all the encodings! As for which pattern we could replace with to be 'general' I was discussing this with some others and the following might work, we can simply change the base (with some caveats later):

```
origlocation:
    cmp rbx,[rip+0xFFFFFFFF] (resolves to absolute address)
->
trampoline:
push rax
mov rax, <origlocation>
cmp rbx,  [rax+0xFFFFFFFF]
pop rax

OR

push rax
mov rax, <absolute address>
cmp rbx,  [rax]
pop rax
```

Either of these will work the first changes the base, the second uses the full register to encode the absolute address instead. There are somes caveats to consider for this.

1) The push and pop touch the stack. This matters for leaf functions which may use data below RSP. Here as an example: https://www.unknowncheats.me/forum/assembly/224583-spoiled-return-value-hooked-function.html. We'd have to first decrement the stack pointer to avoid this red zone/home space (depending on OS). Linux's red zone is 128 bytes, and we have to update this without also changing any cpu flags. As per the link, `lea rsp, [rsp-128]` should work for this, we'll have to undo this on trampoline exit too, and ensure stack is aligned.

2) The temporary register has to be chosen intelligently. In this example the original ` cmp rbx,[rip+0xFFFFFFFF]` uses rbx. If we were to say accidently use `rbx` as our scratch register, we'd break this instruction. Luckily this is simple since our push/pops surround just 1 translated instruction, so our register analysis only has to avoid 1 operand, trivial.

3) Back references, as you correctly pointed out earlier. I've been thinking on this alot. I think for now the simplest way to do this would be to insert 2 short jumps, 1 that jumps the the translated/replaced instruction, and 1 that jumps back after the translated series of instruction is done. Back references only ever point to the start of an overwritten instruction, and short jumps are about as small as any instruction that has a memory operand will be, so we should never be larger than that 1 overwritten instruction. As long as these jmps are smaller, we don't have to consider back references at all while re-writing, this hugely simplifies this whole ordeal. 


Complete example with all caveats. Labels added for clarity:
```
original:
  sub rsp, 12
  mov rbp, rsp
  cmp rbx, [rip+0xFFFFFFFF]
  add rbx, 2
  ret
->
trampoline:
  sub rsp, 12
  mov rbp, rsp
  jmp translation1:
resume:
  add rbx, 2
  ret  

jmp_table:
  <empty>

translation_table:
    translation1:
      lea rsp, [rsp-128]
      push rax
      mov rax, <absolute address>
      cmp rbx, rax
      pop rax
      lea rsp, [rsp+128]
      jmp resume
```

This should actually be pretty general, and I don't think we'd even need a translation map actually. We'd simply just detect RIP relative instructions with memory operands, and re-write like this. We use the stack, but no stack values get spoiled, nor any registers. This should work identically to the current implementation and has no caveats if it's implemented correctly, while supporting all these cases!

**Comment by stevemk14ebr** [comment]
Actually decided to draw out the whole real life example too:

```
original:
  sub rsp, 12
  mov rbp, rsp
  cmp rbx, [rip+0xFFFFFFFF]
  add rbx, 2
  ret

->
// stored in a block allocated +-2GB
hook_addr: &hook

rewritten_original:
  jmp [hook_addr] 
  nop(s)
orig_continue:
  add rbx, 2
  ret

hook (user code):
  <things>
  call trampoline
  ret
  
trampoline:
  sub rsp, 12
  mov rbp, rsp
  jmp translation1:
resume:
  jmp [entry1]

jmp_table:
  entry1: &orig_continue

translation_table:
    translation1:
      lea rsp, [rsp-128]
      push rax
      mov rax, <absolute address>
      cmp rbx, rax
      pop rax
      lea rsp, [rsp+128]
      jmp resume
```

**Comment by acidicoala** [comment]
^ This plan makes perfect sense. Just to clarify, am I correct in assuming that RIP-relative control flow instructions are already handled by polyhook via jump tables? What about the ones like `LOOP` & `LOOPcc`? The last one decrements `RCX` without affecting status flags, because it also checks `ZF`. Perhaps `pushf`, `popf` could be helpful in translating this?

Also, in case it might be useful, I have parsed [this](http://ref.x86asm.net/geek64-abc.html) table of all x64 instructions (including undocumented) that make use of RIP-relative addressing mode. All entries assume `MOD=00` & `R/M=101`:
<details>

| Mnemonic    | OpCode (/ModRM extension)                                                                                                                                               |
|-------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `ADC`       | `10`, `11`, `12`, `13`, `80 /2`, `81 /2`, `83 /2`                                                                                                                       |
| `ADD`       | `00`, `01`, `02`, `03`, `80 /0`, `81 /0`, `83 /0`                                                                                                                       |
| `AND`       | `20`, `21`, `22`, `23`, `80 /4`, `81 /4`, `83 /4`                                                                                                                       |
| `BSF`       | `0FBC`                                                                                                                                                                  |
| `BSR`       | `0FBD`                                                                                                                                                                  |
| `BT`        | `0FA3`, `0FBA /4`                                                                                                                                                       |
| `BTC`       | `0FBA /7`, `0FBB`                                                                                                                                                       |
| `BTR`       | `0FB3`, `0FBA /6`                                                                                                                                                       |
| `BTS`       | `0FAB`, `0FBA /5`                                                                                                                                                       |
| `CALL`      | `FF /2`, `FF /2`                                                                                                                                                        |
| `CMOVB`     | `0F42`                                                                                                                                                                  |
| `CMOVBE`    | `0F46`                                                                                                                                                                  |
| `CMOVL`     | `0F4C`                                                                                                                                                                  |
| `CMOVLE`    | `0F4E`                                                                                                                                                                  |
| `CMOVNB`    | `0F43`                                                                                                                                                                  |
| `CMOVNBE`   | `0F47`                                                                                                                                                                  |
| `CMOVNL`    | `0F4D`                                                                                                                                                                  |
| `CMOVNLE`   | `0F4F`                                                                                                                                                                  |
| `CMOVNO`    | `0F41`                                                                                                                                                                  |
| `CMOVNP`    | `0F4B`                                                                                                                                                                  |
| `CMOVNS`    | `0F49`                                                                                                                                                                  |
| `CMOVNZ`    | `0F45`                                                                                                                                                                  |
| `CMOVO`     | `0F40`                                                                                                                                                                  |
| `CMOVP`     | `0F4A`                                                                                                                                                                  |
| `CMOVS`     | `0F48`                                                                                                                                                                  |
| `CMOVZ`     | `0F44`                                                                                                                                                                  |
| `CMP`       | `38`, `39`, `3A`, `3B`, `80 /7`, `81 /7`, `83 /7`                                                                                                                       |
| `CMPXCHG`   | `0FB0`, `0FB1`                                                                                                                                                          |
| `CRC32`     | `F20F38F0`, `F20F38F1`                                                                                                                                                  |
| `CVTSI2SD`  | `F20F2A`                                                                                                                                                                |
| `CVTSI2SS`  | `F30F2A`                                                                                                                                                                |
| `DEC`       | `FE /1`, `FF /1`                                                                                                                                                        |
| `DIV`       | `F6 /6`, `F7 /6`                                                                                                                                                        |
| `EXTRACTPS` | `660F3A17`                                                                                                                                                              |
| `HINT_NOP`  | `0F18 /4`, `0F18 /5`, `0F18 /6`, `0F18 /7`, `0F19`, `0F1A`, `0F1B`, `0F1C`, `0F1D`, `0F1E`, `0F1F /1`, `0F1F /2`, `0F1F /3`, `0F1F /4`, `0F1F /5`, `0F1F /6`, `0F1F /7` |
| `IDIV`      | `F6 /7`, `F7 /7`                                                                                                                                                        |
| `IMUL`      | `69`, `6B`, `F6 /5`, `F7 /5`, `0FAF`                                                                                                                                    |
| `INC`       | `FE /0`, `FF /0`                                                                                                                                                        |
| `JMP`       | `FF /4`, `FF /4`                                                                                                                                                        |
| `LLDT`      | `0F00 /2`                                                                                                                                                               |
| `LMSW`      | `0F01 /6`                                                                                                                                                               |
| `LTR`       | `0F00 /3`                                                                                                                                                               |
| `MOV`       | `88`, `89`, `8A`, `8B`, `8E`, `C6 /0`, `C7 /0`                                                                                                                          |
| `MOVD`      | `0F6E`, `660F6E`, `0F7E`, `660F7E`                                                                                                                                      |
| `MOVSX`     | `0FBE`, `0FBF`                                                                                                                                                          |
| `MOVSXD`    | `63`                                                                                                                                                                    |
| `MOVZX`     | `0FB6`, `0FB7`                                                                                                                                                          |
| `MUL`       | `F6 /4`, `F7 /4`                                                                                                                                                        |
| `NEG`       | `F6 /3`, `F7 /3`                                                                                                                                                        |
| `NOP`       | `0F0D`, `0F1F /0`                                                                                                                                                       |
| `NOT`       | `F6 /2`, `F7 /2`                                                                                                                                                        |
| `OR`        | `08`, `09`, `0A`, `0B`, `80 /1`, `81 /1`, `83 /1`                                                                                                                       |
| `PEXTRD`    | `660F3A16`                                                                                                                                                              |
| `PINSRD`    | `660F3A22`                                                                                                                                                              |
| `POP`       | `8F /0`, `8F /0`                                                                                                                                                        |
| `POPCNT`    | `F30FB8`                                                                                                                                                                |
| `PUSH`      | `FF /6`, `FF /6`                                                                                                                                                        |
| `RCL`       | `C0 /2`, `C1 /2`, `D0 /2`, `D1 /2`, `D2 /2`, `D3 /2`                                                                                                                    |
| `RCR`       | `C0 /3`, `C1 /3`, `D0 /3`, `D1 /3`, `D2 /3`, `D3 /3`                                                                                                                    |
| `ROL`       | `C0 /0`, `C1 /0`, `D0 /0`, `D1 /0`, `D2 /0`, `D3 /0`                                                                                                                    |
| `ROR`       | `C0 /1`, `C1 /1`, `D0 /1`, `D1 /1`, `D2 /1`, `D3 /1`                                                                                                                    |
| `SAL`       | `C0 /6`, `C1 /6`, `D0 /6`, `D1 /6`, `D2 /6`, `D3 /6`                                                                                                                    |
| `SAR`       | `C0 /7`, `C1 /7`, `D0 /7`, `D1 /7`, `D2 /7`, `D3 /7`                                                                                                                    |
| `SBB`       | `18`, `19`, `1A`, `1B`, `80 /3`, `81 /3`, `83 /3`                                                                                                                       |
| `SETB`      | `0F92 /0`                                                                                                                                                               |
| `SETBE`     | `0F96 /0`                                                                                                                                                               |
| `SETL`      | `0F9C /0`                                                                                                                                                               |
| `SETLE`     | `0F9E /0`                                                                                                                                                               |
| `SETNB`     | `0F93 /0`                                                                                                                                                               |
| `SETNBE`    | `0F97 /0`                                                                                                                                                               |
| `SETNL`     | `0F9D /0`                                                                                                                                                               |
| `SETNLE`    | `0F9F /0`                                                                                                                                                               |
| `SETNO`     | `0F91 /0`                                                                                                                                                               |
| `SETNP`     | `0F9B /0`                                                                                                                                                               |
| `SETNS`     | `0F99 /0`                                                                                                                                                               |
| `SETNZ`     | `0F95 /0`                                                                                                                                                               |
| `SETO`      | `0F90 /0`                                                                                                                                                               |
| `SETP`      | `0F9A /0`                                                                                                                                                               |
| `SETS`      | `0F98 /0`                                                                                                                                                               |
| `SETZ`      | `0F94 /0`                                                                                                                                                               |
| `SHL`       | `C0 /4`, `C1 /4`, `D0 /4`, `D1 /4`, `D2 /4`, `D3 /4`                                                                                                                    |
| `SHLD`      | `0FA4`, `0FA5`                                                                                                                                                          |
| `SHR`       | `C0 /5`, `C1 /5`, `D0 /5`, `D1 /5`, `D2 /5`, `D3 /5`                                                                                                                    |
| `SHRD`      | `0FAC`, `0FAD`                                                                                                                                                          |
| `SUB`       | `28`, `29`, `2A`, `2B`, `80 /5`, `81 /5`, `83 /5`                                                                                                                       |
| `TEST`      | `84`, `85`, `F6 /0`, `F6 /1`, `F7 /0`, `F7 /1`                                                                                                                          |
| `UD`        | `0FB9`                                                                                                                                                                  |
| `VERR`      | `0F00 /4`                                                                                                                                                               |
| `VERW`      | `0F00 /5`                                                                                                                                                               |
| `VMREAD`    | `0F78`                                                                                                                                                                  |
| `VMWRITE`   | `0F79`                                                                                                                                                                  |
| `XADD`      | `0FC0`, `0FC1`                                                                                                                                                          |
| `XCHG`      | `86`, `87`                                                                                                                                                              |
| `XOR`       | `30`, `31`, `32`, `33`, `80 /6`, `81 /6`, `83 /6`                                                                                                                       |
</details>

**Comment by stevemk14ebr** [comment]
```
Just to clarify, am I correct in assuming that RIP-relative control flow instructions are already handled by polyhook via jump tables
```

This is correct. Any branching instructions that are RIP relative are simply updated to point to an intermediate jump if they are too small to hold their displacement. Even things like loop should be handled, if it's not then that is a bug. 

Your table is awesome thanks, that will be a help to verify this works during testing and covers all the cases.

**Comment by acidicoala** [comment]
Hello. I wanted to ask about max displacement calculation done by PH2. In this example when Capstone is used:
```
[+] Info: Prologue to overwrite:
7ffca363b4c0 [7]: 83 3d a5 7e 09 00 00          cmp dword ptr [rip + 0x97ea5], 0 -> 7ffca36d336c

[!] Error: Cannot fixup IP relative data operation, needed disp. beyond max disp range: cmp dword ptr [rip + 0x97ea5], 0 needed: 0x00007d77aeaa2340 raw: 0xffff82885155dcc0 max: 0x0000007fffffffff
```
Polyhook thinks that max value can store 5 bytes. Shouldn't it be 4 bytes? PH2 calculates this value (in `copyDispSx`) by subtracting displacement offset (2) from instruction size (7), however it fails to take into account immediate offset (6) that is present in RIP-relative data operations. The fix for that is quite trivial, since Capstone provides immediate offset (`x86.encoding.imm_offset`).

When using Zydis the situation is even more sad:
```
[+] Info: Prologue to overwrite:
7ffca363b4c0 [7]: 83 3d a5 7e 09 00 00          cmp dword ptr ds:[0x00007FFCA36D336C], 0x00 -> 7ffca363b4c7

[!] Error: Cannot fixup IP relative data operation, needed disp. beyond max disp range: cmp dword ptr ds:[0x00007FFCA36D336C], 0x00 needed: 0x00007d92195fb520 raw: 0xffff826de6a04ae0 max: 0x000000000000007f
```
The max displacement got calculated as 1 byte. After debugging it, it became clear that when parsing 2nd operand of the `cmp` instruction (which is 1 byte immediate value) the `inst.setDisplacementOffset` function call overwrites previously saved displacement. Once again, the fix is trivial, we just need to store the immediate offset (`zydisInst->raw.imm->offset`) in a separate field the `PLH::Instruction` structure.

Hope this helps with implementation of the RIP-relative instruction substitution. Have you had a chance to look at it in more detail by the way? I was trying to implement it on my own when I discovered the above-mentioned issues.

**Comment by stevemk14ebr** [comment]
I haven't had time to look into implementing the changes we talked about yet. There's definitely a bug with the instruction displacement max value calculation here though, thanks for identifying this! You're right that this is related to the immediate value, but I don't think it has anything to do with RIP relative, the last byte of the instruction holds the immediate value to compare against and I incorrectly include this in the displacement size. I checked this with the ZydisInfo tool:

Input bytes:
```
83 3d a5 7e 09 00 01
```
```
== [    BASIC ] ============================================================================================
   MNEMONIC: cmp [ENC: DEFAULT, MAP: DEFAULT, OPC: 0x83]
     LENGTH:  7
        SSZ: 64
       EOSZ: 32
       EASZ: 64
   CATEGORY: BINARY
    ISA-SET: I86
    ISA-EXT: BASE
 EXCEPTIONS: NONE
 ATTRIBUTES: HAS_MODRM IS_RELATIVE CPUFLAG_ACCESS ACCEPTS_SEGMENT
  OPTIMIZED: 83 3D A5 7E 09 00 01

== [ OPERANDS ] ============================================================================================
##       TYPE  VISIBILITY  ACTION      ENCODING   SIZE  NELEM  ELEMSZ  ELEMTYPE                        VALUE
--  ---------  ----------  ------  ------------   ----  -----  ------  --------  ---------------------------
 0     MEMORY    EXPLICIT       R      MODRM_RM     32      1      32       INT  TYPE  =                 MEM
                                                                                 SEG   =                  ds
                                                                                 BASE  =                 rip
                                                                                 INDEX =                none
                                                                                 SCALE =                   0
                                                                                 DISP  =  0x0000000000097EA5
 1  IMMEDIATE    EXPLICIT       R         SIMM8      8      1       8       INT  [S A  8] 0x0000000000000001
 2   REGISTER      HIDDEN       W          NONE     64     64       1       INT                       rflags
--  ---------  ----------  ------  ------------   ----  -----  ------  --------  ---------------------------

== [    FLAGS ] ============================================================================================
    ACTIONS: [CF  : M  ] [PF  : M  ] [AF  : M  ] [ZF  : M  ] [SF  : M  ] [OF  : M  ]
       READ: 0x00000000
    WRITTEN: 0x000008D5

== [      ATT ] ============================================================================================
   ABSOLUTE: cmpl $0x01, 0x0000000000097EAC
   RELATIVE: cmpl $0x01, 0x97EA5(%rip)

== [    INTEL ] ============================================================================================
   ABSOLUTE: cmp dword ptr ds:[0x0000000000097EAC], 0x01
   RELATIVE: cmp dword ptr ds:[rip+0x97EA5], 0x01

== [ SEGMENTS ] ============================================================================================
83 3D A5 7E 09 00 01
:  :  :           :..IMM
:  :  :..DISP
:  :..MODRM
:..OPCODE
```

The fix for capstone looks easy enough, just add a check to subtract off the immediate value when it's present. For zydis the fix should be to ignore the immediate value when calling `setDisplacementOffset` if that value isn't the one used in the MEM calculation (Immediate values should only be stored really for jmp or call types where the immediate is literally the jump target). 

Would you be willing to try a PR with some Unit Tests? If not I can fix this myself. Thanks for the report.

**Comment by stevemk14ebr** [comment]
I think I fixed the issue for zydis in this commit here: https://github.com/stevemk14ebr/PolyHook_2_0/commit/b9618c9f9455fdcea78ebe9add229bf073e3045d. It may be a while before I merge this. I decided that when I implement all the things we discussed before I am also going to drop capstone support. Since this is an x86/x64 only library I think this makes sense.

**Comment by acidicoala** [comment]
Thanks a lot for the quick fix for this. I didn't know about the `rm_capstone` branch. Your reasons for removal make sense. I will be experimenting on that branch from now on.

**Comment by acidicoala** [comment]
@stevemk14ebr, unfortunately the issue is still present in `rm_capstone` even with the latest fix. The error with zydis is now the same as it was in capstone: `Size - Displacement` calculation that does not take immediate into account when calculating displacement size. I can fix this issue if you want.

P.S. Here is a unit test I'm using for RIP-relative tests: https://github.com/acidicoala/PolyHook_2_0/blob/fecdd8943c93c58518e19a478a1321bb47c8d0f3/UnitTests/windows/TestDetourx64.cpp#L124-L146

P.S.S. There was a member visibility issue in TestDisassembler.cpp which I quickly addressed [here](https://github.com/acidicoala/PolyHook_2_0/blob/fecdd8943c93c58518e19a478a1321bb47c8d0f3/UnitTests/windows/TestDisassembler.cpp#L404), but perhaps you want to consider the proper solution because in that unit test the rest of the member access is done using direct member rather than getter.

**Comment by stevemk14ebr** [comment]
Ah yea ok, if you would like to take a stab at fixing this https://github.com/acidicoala/PolyHook_2_0/blob/750e78f8d7ebfc291e1c0dce3a0763c3a4b86737/polyhook2/Instruction.hpp#L167 I'd merge. The member visibility is also fine, I'd merge that too. Thanks for the continued testing!

**Comment by acidicoala** [comment]
Can we safely assume that if an instruction is big enough to hold rip-relative operation (which should be at least 5 bytes in size), then it is big enough for a +-2gb jmp (which is exactly 5 bytes in size)? 

Also, if the rip-relative operation is bigger then 5 bytes then I'm assuming we need to insert `nop`s between it and the next instruction so as to preserve relative instruction addresses?

Finally, is it correct to assume that the process for finding a suitable memory location should be the same as the one implemented in `makeTrampoline` function? i.e. repeat *n* times until we got memory location that is within +-2gb range from the instruction that needs to be translated? If yes, then can we extract that functionality into a utility function to facilitate reusability?

**Comment by SNMetamorph** [comment]
It'll be cool if this will fixed. I faced with this issue in my project.

**Comment by stevemk14ebr** [comment]
@SNMetamorph try the rm_capstone branch, it implements this thanks to @acidicoala

**Comment by acidicoala** [comment]
Things are looking quite grim on vcpkg front. They won't merge asmjit update until fbgemm has migrated to the latest asmjit as well. There is no indication that fbgemm maintainers are going to update to latest asmjit, which introduces breaking changes.

I did everything I could to port it to vcpkg (asmjit port, asmtk CMake + port, polyhook2 port), but it still wasn't enough. Due to this this all-or-nothing ideology from vcpkg (and other broken ports on vcpkg, such as cpr), I will be migrating away from vcpkg. I am considering Conan, which handles version resolution properly, but it is missing packages for AsmTk and Zydis, and of course Polyhook. Not sure if I can find the will to submit all 3 packages, because conan documentations mentions:
> Maintenance commitment: You are responsible for keeping the recipe updated, fix issues etc., so be aware that a minimal commitment is required. The Conan organization reserves the right to unlink a poorly maintained package or replace it with better alternatives.

So, it seems like a good old git submodule is the go-to solution for now.

**Comment by stevemk14ebr** [comment]
I'll try to push the vcpkg forward myself, thank you! I'm going to merge to master then so help move that along. Vcpkg is annoying for sure...

**Comment by stevemk14ebr** [comment]
Closing with bf375cfe60809faed0b4362de31b051cb792dadd
