### ISSUE TITLE
Deliberate placement of code-caves

### ISSUE THREAD

**Issue by acidicoala** [stevemk14ebr/PolyHook_2_0#121]
Good day. A while ago I encountered an issue where a Release build of a DLL (x64), that was performing some detouring logic using PH2 library, was taking up to a minute to hook each function. A Debug build of the same project did not have such issue and hooking was instantaneous. When specifying detour scheme, only code cave worked, so I came to conclusion that the issue is not present in Debug build because it contains numerous code-caves that drastically reduce search time. My question is: can we somehow "bake in" code caves into our binary builds, so that even Release builds would contain said code caves?

**Comment by stevemk14ebr** [comment]
You can probably use some compiler intrinsics or put a large C style array at global scope to help. But you should check if the CODE_CAVE strategy actually ended up working or not, or if the INPLACE is what it finally fell back to
