### ISSUE TITLE
The lib file `asmtk.lib` not install to folder `_install/lib`

### ISSUE THREAD

**Issue by halx99** [stevemk14ebr/PolyHook_2_0#135]
RT

**Comment by stevemk14ebr** [comment]
Can you send a PR to fix?

**Comment by stevemk14ebr** [comment]
@acidicoala any ideas what might be the issue here?

**Comment by acidicoala** [comment]
I don't understand the issue here since no description is given. In general, every issue should have instructions on how to reproduce reported issue.

Polyhooks links the same way as it used to, by the way. It's just that it now supports inclusion via CMake's `add_subdirectory` command.

**Comment by stevemk14ebr** [comment]
@halx99 if you can provide more details about the commands you're running as well as the issue you're hitting - we can provide more help

**Comment by halx99** [comment]
I use follow commands (from README.md) to build and install:
```bat
cmake -B"./_build" -DCMAKE_INSTALL_PREFIX="./_install/"
cmake --build "./_build" --config Release --target INSTALL
```

And the `./_install/lib` folder looks like follow(no asmtk.lib):
![image](https://user-images.githubusercontent.com/6977319/170411311-1c9aad15-adc2-46fb-981d-6c10fcc3fe59.png)

**Comment by acidicoala** [comment]
Waiting for https://github.com/asmjit/asmtk/pull/26

**Comment by stevemk14ebr** [comment]
thanks for working this @acidicoala  :)
