### ISSUE TITLE
Syscalls when NTVirtualProtect is hooked?

### ISSUE THREAD

**Issue by illumen** [stevemk14ebr/PolyHook_2_0#140]
Hi,

Thanks for a great library.
What is your recommended way to make sure PLH uses sycalls if NTProtectVirtualMemory / VirtualProtect is hooked?

**Comment by luciouskami** [comment]
I've thought about this before, but it requires a universal solution for syscall (x86/x64/wow64)

**Comment by stevemk14ebr** [comment]
All of the virtualprotect calls are invoked from the parent class `MemProtector`. Each hook class derives from this (https://github.com/stevemk14ebr/PolyHook_2_0/blob/master/polyhook2/MemProtector.hpp). You can inherit from the hook type and overload these protection member functions to dispatch direct system calls yourself.
