### ISSUE TITLE
how to hook a non static member function in the class?

### ISSUE THREAD

**Issue by evehal** [stevemk14ebr/PolyHook_2_0#142]
```
for example
class TestClass {
public:
	bool Test() {
		return false;
	}
};
NOINLINE bool __cdecl CanAddNewLocalVariable_() {
	return false;
}
uint64_t hookPrintfTramp = NULL;
PLH::x64Detour* detour = new PLH::x64Detour((uint64_t)(&TestClass::Test), (uint64_t)&CanAddNewLocalVariable_, &hookPrintfTramp);
```
it not compiled

**Comment by stevemk14ebr** [comment]
You need to get a pointer to the member function. After you get that, you can pass the address to polyhook as normal. 

There's no way to do this in conformant C++, member function pointers are fat pointers and how to find the underlying address of a function isn't possible without non-portable hacks. You can try some things like this: https://stackoverflow.com/questions/11048176/detouring-a-member-function-via-an-injected-dll
