### ISSUE TITLE
Updating VCPKG version

### ISSUE THREAD

**Issue by veteri** [stevemk14ebr/PolyHook_2_0#143]
Would you consider updating the version on vcpkg to reflect the various recent bugfixes?

**Comment by stevemk14ebr** [comment]
We're waiting on upstream projects to update their forks first. Facebooks FBGEMM is our main issue as it's blocking the other port updates, you can see this here 

https://github.com/pytorch/FBGEMM/issues/1070

**Comment by stevemk14ebr** [comment]
https://github.com/microsoft/vcpkg/pull/24362#issuecomment-1108584210

**Comment by veteri** [comment]
Thanks for the info. Looking forward to the update.

**Comment by itisluiz** [comment]
Also waiting on this

**Comment by stevemk14ebr** [comment]
waiting on this, still blocked by not having asmtk or the latest asmjit. That can't happen until https://github.com/pytorch/FBGEMM/issues/1291 is resolved.

**Comment by stevemk14ebr** [comment]
current work on this is here: https://github.com/microsoft/vcpkg/pull/27683#issuecomment-1320421698
(cc @acidicoala)

**Comment by stevemk14ebr** [comment]
This is resolved! The vcpkg installation has been updated and points at master
