### ISSUE TITLE
`VirtualAlloc2` with `MEM_ADDRESS_REQUIREMENTS` must respect min/max application addresses

### ISSUE THREAD

**Issue by alexrp** [stevemk14ebr/PolyHook_2_0#147]
Hey,

I've been working on a modern injection/hooking framework in C# and I wanted to use `VirtualAlloc2` with `MEM_ADDRESS_REQUIREMENTS` to allocate hook memory, rather than the classic `VirtualQuery` loop approach. I ran into the issue of getting an inscrutable "invalid parameter" error, though. After some searching around, I came upon this project and your discovery that the low/high addresses must be aligned to the system's allocation granularity. So thanks for that!

I noticed some intermittent allocation failures in my project's CI, though. It turns out that there are additional constraints on the low/high address: They must respect the `lpMinimumApplicationAddress`/`lpMaximumApplicationAddress` fields of the `SYSTEM_INFO` structure. Notably, those fields always satisfy the alignment constraints of `VirtualAlloc2`, which makes this case fairly simple to handle.

https://github.com/vezel-dev/ruptura/blob/2593e28b5125795f173ebe4ceff0df7d08dfc25c/src/memory/Code/PageCodeManager.cs#L258-L283

**Comment by stevemk14ebr** [comment]
Oh that's interesting, thank you for finding and documenting this! Would you be willing to take a try at a PR to polyhook to fix this?

**Comment by stevemk14ebr** [comment]
No worries at all, I will implement it eventually if you don't get to it. I think the way it works now is mostly fine, I take care for 32bit processes to not stay within this range iirc, it's just not as nice as using the value from the API as you've shown
