### ISSUE TITLE
PLH::findPattern fails due to issue with _alloca

### ISSUE THREAD

**Issue by itisluiz** [stevemk14ebr/PolyHook_2_0#149]
On Windows, using C++ 17 compiled for x86_64 with MSVC 1932, I'm getting a weird issue where `PLH::findPattern` will actually look the character 'x' (0x78) in memory instead of whichever bytes I provided on the signature. 

Upon further inspection, I managed to pin down the issue on the allocations of `patt_base` and `msk_base`. The issue is that `PolyHook2Alloca` is returning the same allocated address for both variables.

![debbuger](https://i.imgur.com/YC5mhRP.png)

**Comment by stevemk14ebr** [comment]
I darn, whoever wrapped alloca forgot it's mem is freed on function exit. This function polyhookalloca function needs a forceinline attribute added. Feel like sending a PR?
