### ISSUE TITLE
Including polyhook makes my code crash on launch

### ISSUE THREAD

**Issue by sbtoonz** [stevemk14ebr/PolyHook_2_0#154]
Unsure how to debug this since I cant even hit the APIENTRY for my .dll 

when I use PolyHook2 and its associated static libs 

Zycore.lib
Zydis.lib
asmjit.lib
asmtk.lib
PolyHook_2.lib

the test no longer loads ... at all

Steps to reproduce:

1) Make new DLL C++ project in VS/Rider/Whatever
2) 

place this code in the "main.dll"

```
#define _CRT_SECURE_NO_WARNINGS
#include "Main.h"
#include <windows.h>
#include <fstream>
#include <iomanip>
#include <string>
#include <iostream>
#include <psapi.h>
#include <dxgi1_4.h>
using namespace  std;

int main()
{
    DisableThreadLibraryCalls(hModule);
    AllocConsole();
    freopen("CONOUT$", "w", stdout);
    std::cout << "injected" << std::endl;
    return 0;
}
```

3) Compile -> inject ... watch the console open and display your text.

4) Simply link PolyHook (via linker or by adding it as a dependency) -> compile 
5) inject DLL from step 4.... Console no longer Allocs...

It crashes so fast I cant even get the debugger to break on it

**Comment by sbtoonz** [comment]
Possible non issue, if I create the DLL project within the polyhook solution everything works?

**Comment by stevemk14ebr** [comment]
it's possible your other dll has imports that aren't being resolved at load time. Inspect the library dependencies, or use a different inector that gives better output, or debug at dll load time.

**Comment by sbtoonz** [comment]
```
0>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\link.exe /ERRORREPORT:PROMPT /OUT:"C:\Users\USERNAMEHER\RiderProjects\PolyHook_2_0\x64\Debug\TestPolyHook.dll" /INCREMENTAL /ILK:"x64\Debug\TestPolyHook.ilk" /NOLOGO /LIBPATH:"C:\Users\USERNAMEHER\RiderProjects\vcpkg\installed\x64-windows\debug\lib" /LIBPATH:"C:\Users\USERNAMEHER\RiderProjects\vcpkg\installed\x64-windows\debug\lib\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "C:\Users\USERNAMEHER\RiderProjects\vcpkg\installed\x64-windows\debug\lib\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\Users\USERNAMEHER\RiderProjects\PolyHook_2_0\x64\Debug\TestPolyHook.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Users\USERNAMEHER\RiderProjects\PolyHook_2_0\x64\Debug\TestPolyHook.lib" /MACHINE:X64 /DLL x64\Debug\dllmain.obj
C:\Users\USERNAMEHER\RiderProjects\PolyHook_2_0\asmtk\Debug\asmjit.lib
C:\Users\USERNAMEHER\RiderProjects\PolyHook_2_0\asmtk\Debug\asmtk.lib
C:\Users\USERNAMEHER\RiderProjects\PolyHook_2_0\zydis\dependencies\zycore\Debug\Zycore.lib
C:\Users\USERNAMEHER\RiderProjects\PolyHook_2_0\zydis\Debug\Zydis.lib
C:\Users\USERNAMEHER\RiderProjects\PolyHook_2_0\Debug\PolyHook_2.lib
0>TestPolyHook.vcxproj -> C:\Users\USERNAMEHER\RiderProjects\PolyHook_2_0\x64\Debug\TestPolyHook.dll
```

I was almost positive it was getting packed as the output is 1:1 from the "standalone" project using linker 
the standalone project using references
and the project added to the Solution generated by polyhook Cmake



I am going to have to reopen this issue as it is present even if I build this DLL within PolyHook Solution


Steps to replicate:

git clone --recursive https://github.com/stevemk14ebr/PolyHook_2_0.git
cd PolyHook_2.0
cmake . 

Method A:
Open the generated SLN
Right click -> Add new -> C++ DLL 
Name it whatever its for a test
Right click "Dependencies" and add the PolyHook_2.0/asmjit/asmtk/Zycore/Zydis as project dependencies

paste code from initial issue open 

Elect to add your PLH hook (x86/64 whatever it may be) in my use case it was an x64Detour* detour = new x64Detour(fnAdd, fnCallback, userTrampVar)

Build project (check build log to ensure libs are linked) 
inject DLL I now no longer get console even acknowledging DLL is running 


Method B:
Open the generated SLN
click build for "build all"
relaunch VS /Rider as admin and build the "INSTALL" target 
PolyHook installs to ProgramFilesX86

Right click -> Add new -> C++ DLL 
Name it whatever its for a test
Right click the new project
go to C++ and include the "PolyHook2_0" build dir and add the folder called "includes"  as extern includes
go to linker tab and add the "PolyHook2_0" build dir folder called "lib" to the library folder 
go to linker additional dependencies
add:
PolyHook_2.lib
Zydis.lib
Zycore.lib
asmtk.lib
asmjit.lib


paste code from initial issue open 

Elect to add your PLH hook (x86/64 whatever it may be) in my use case it was an x64Detour* detour = new x64Detour(fnAdd, fnCallback, userTrampVar)

Build project (check build log to ensure libs are linked) 
inject DLL I now no longer get console even acknowledging DLL is running 




Stupid question but how to debug C++ dll at runtime when they dont produce an exe ... this is my first forray into C++ stuff so forgive me ... in C# I just attach process set breakpoint and wait for break then do my debugging from there by stepping through stuff / editing the memory in debugger etc 

i am not sure how to execute this work flow in my current scenario as this is being applied to an exe i have no control over since I didnt produce the exe I am trying to inject the dll into

**Comment by sbtoonz** [comment]
https://stevemk14ebr.github.io/PolyHook_2_0/

Wish this was easier to find putzing around the internet.. the other documentation seems centric to polyhook1.0

**Comment by EzequielDM** [comment]
Also having issues with this, tried both vcpkg and manually building PolyHook and static linking the libraries

**Comment by stevemk14ebr** [comment]
I need someone to debug what's happening before I can triage this

**Comment by sbtoonz** [comment]
I just switched to minhook 
This issue is now a non issue

**Comment by stevemk14ebr** [comment]
Lol
