### ISSUE TITLE
Expose m_hooked boolean

### ISSUE THREAD

**Issue by itisluiz** [stevemk14ebr/PolyHook_2_0#155]
Why isn't [m_hooked](https://github.com/stevemk14ebr/PolyHook_2_0/blob/4247138b14c5a95a203b0672a6f1a4fcca0faa4f/polyhook2/IHook.hpp#L63) exposed through a getter in the IHook interface? Wrappers have to resort to tracking the calls to hook() and unHook() along with the trampoline variable. Seems like it would be a good idea to have it exposed.

**Comment by stevemk14ebr** [comment]
sure it can be
