### ISSUE TITLE
Disassembler may go out of bounds into unmapped region

### ISSUE THREAD

**Issue by EngineLessCC** [stevemk14ebr/PolyHook_2_0#159]
I've encountered an edge-case at the following lines:

sources/x64Detour.cpp#L299
sources/ADetour.cpp#L72

> dest + 100

May end up going beyond mapped memory and cause an av.

**Comment by stevemk14ebr** [comment]
Thanks, you're right. https://github.com/stevemk14ebr/PolyHook_2_0/blob/master/sources/ZydisDisassembler.cpp#L51 should be safe_mem_read instead
