### ISSUE TITLE
Use wstring_view instead of wstring

### ISSUE THREAD

**Issue by Randshot** [stevemk14ebr/PolyHook_2_0#16]
https://github.com/stevemk14ebr/PolyHook_2_0/blob/007ce9df7f90c9df470b37f1fe7667de720acd6e/sources/EatHook.cpp#L101-L106
Why don't you use `std::wstring_view` in combination with `std::wstring_view::compare` here? 
**Edit:** Never mind, didn't notice the case-insensitive compare.
Maybe something like this:
```cpp
std::wstring_view baseModuleName(dte->BaseDllName.Buffer, dte->BaseDllName.Length / sizeof(wchar_t));
auto const icmp = [](wchar_t const& a, wchar_t const& b) noexcept -> bool { return towlower(a) == towlower(b); };

// try all modules if none given, otherwise only try specified
if (!moduleName.empty() && !std::equal(moduleName.cbegin(), moduleName.cend(), baseModuleName.cbegin(),
        baseModuleName.cend(), icmp))
    continue;
```
Haven't tested how it compares performance wise.

**Comment by Randshot** [comment]
Ok, it's your project.
Most of the time though, it will be as fast if not faster than a quick implementation you write yourself.
And it also defeats the purpose of stating that this is a **C++17** library IMO.

**Comment by Randshot** [comment]
Then how about creating a modified `char_traits<>` type which compares case-insensitively.

**Comment by stevemk14ebr** [comment]
I quite like that solution. If you are interested in implementation I'd merge a PR? If not I can see when I get around to this 😊

**Comment by stevemk14ebr** [comment]
You can place this in Misc.hpp
