### ISSUE TITLE
VEH Hook function

### ISSUE THREAD

**Issue by LYingSiMon** [stevemk14ebr/PolyHook_2_0#165]
hello，Can we add VEH Hook functionality ？（For example, set the memory property to No Access）
Because some programs check EAT and IAT，and use crc to detect inline hooks and software breakpoints，but hardware breakpoints only four can be used. 

😭

**Comment by stevemk14ebr** [comment]
There is an implementation of this in polyhook v1. I am not sure if I will include this in polyhook 2. You're welcome to submit a PR though and I'll review
