### ISSUE TITLE
The best API hooking library ever made, just thank you

### ISSUE THREAD

**Issue by MurylloEx** [stevemk14ebr/PolyHook_2_0#197]
I'm writing this issue but it's not really an issue, It's just a thank you for your commitment to this brilliant library.
I looked for several candidates, yours was the only one that allowed me to read the code well and learn the hooks in a readable way.

**Comment by stevemk14ebr** [comment]
Thanks for saying so, I love messages like this. Really happy to help! I read your profile, fun fact, I started in VB.NET as a child too!
