### ISSUE TITLE
AsmJit update in vcpkg breaks polyhook

### ISSUE THREAD

**Issue by kobalicek** [stevemk14ebr/PolyHook_2_0#201]
Would it be possible to update polyhook to support the latest asmjit?

  - https://github.com/microsoft/vcpkg/pull/39090

There was one API change which doesn't have deprecation and unfortunately polyhook stopped building.

**Comment by stevemk14ebr** [comment]
Completed in https://github.com/stevemk14ebr/PolyHook_2_0/commit/796de83bd2f5cf2b56a24b75f49ea318bbb5e9d9

**Comment by kobalicek** [comment]
Amazing thanks!
