### ISSUE TITLE
cli noise

### ISSUE THREAD

**Issue by dnblank123** [stevemk14ebr/PolyHook_2_0#208]
is there a way to turn off this? im using the latest commit https://github.com/stevemk14ebr/PolyHook_2_0/commit/19e7cec8cce4a0068f6db04b6d3680c078183002
> Generate API documentation for ZycoreDoc
Doxygen version used: 1.11.0
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...

**Comment by stevemk14ebr** [comment]
I bet zydis has a compilation flag or variable that can be set. I'd try searching the zydis documentation or it's cmake file first.

**Comment by dnblank123** [comment]
> I bet zydis has a compilation flag or variable that can be set. I'd try searching the zydis documentation or it's cmake file first.

Thank you, manage to find it was on ```\polyhook\zydis\dependencies\zycore\CMakeLists.txt @ 229```
