### ISSUE TITLE
Hooking Directx11

### ISSUE THREAD

**Issue by Icesythe7** [stevemk14ebr/PolyHook_2_0#30]
I was just curious  if there is a way to hook directx when an overlay already has it hooked (ie discord, steam, etc) if I do not disable these overlays then polyhook will fail with "[!] Error: Function too small to hook safely!" is there anything that I should be doing differently so that I can hook when overlays have hooked as well? 
(this is currently happening on directx11 x64, doesnt seem to have any issue with directx9 and x86)

**Comment by maxkunes** [comment]
So it looks like the problem here is lack of support for hooking functions that are already hooked. @stevemk14ebr would have to be the one to comment on that, but @Icesythe7, have you tried to instead hook the overlay's render function? Aka actually hook their function rather than trying to hook over their hook?

**Comment by Icesythe7** [comment]
While that may work it defeats the purpose of the point of the library I use, furthermore my library supports all directx programs and discord does not thus expanding my lib to check for pre-existing hooks and then hook their overlay could cause issues down the road if say the discord is turned off mid game any functions using that hooks thread will most likely instantly crash on the next call.

**Comment by stevemk14ebr** [comment]
The library already attempts to follow jumps in the prologue (meaning already hooked functions). There's alot of ways to redirect execution though and especially on x64 people use intermediate registers, which can't be resolved without full on emulation. If you post the assembly in question I can tell you why it failed and if there's a workaround. 

https://github.com/stevemk14ebr/PolyHook_2_0/blob/9f239bbd2087709e76fdab22a1291ab3a60a604f/sources/x64Detour.cpp#L48
