### ISSUE TITLE
cmake 太操蛋了,能不能转换成vs项目

### ISSUE THREAD

**Issue by fysu** [stevemk14ebr/PolyHook_2_0#32]
cmake 太操蛋了,能不能转换成vs项目

**Comment by stevemk14ebr** [comment]
No I will not convert to a vs project you can do that with cmake itself if you want, and it's not fucked as it is. Speak English please

**Comment by zhangyfan** [comment]
CMake很容易生成VS项目啊，怎么操蛋了？
It is very easy to generate VS solution with cmake.
