### ISSUE TITLE
"Bug" in hw:bp based hook

### ISSUE THREAD

**Issue by lyn1k** [stevemk14ebr/PolyHook_2_0#33]
> LONG PLH::HWBreakPointHook::OnException(EXCEPTION_POINTERS* ExceptionInfo) {
> 	if (ExceptionInfo->ExceptionRecord->ExceptionCode != EXCEPTION_SINGLE_STEP)
> 		return EXCEPTION_CONTINUE_EXECUTION;
> 	ExceptionInfo->ContextRecord->Dr7 &= ~(1ULL << (2 * m_regIdx));
> 	ExceptionInfo->ContextRecord->XIP = (decltype(ExceptionInfo->ContextRecord->XIP))m_fnCallback;
> 	return EXCEPTION_CONTINUE_EXECUTION;
> }
> 

I'd do `	if (ExceptionInfo->ExceptionRecord->ExceptionCode != EXCEPTION_SINGLE_STEP)
		return EXCEPTION_CONTINUE_SEARCH;`
 instead. Someone asked me why their hw:bp is crashing the application, after i looked at this code it was obvious because the application is intentionally triggering exceptions with instructions like `hlt` or `wbinvd` to change control flow to their VEH's, this here however will prevent those Exceptionhandlers from being called.

**Comment by stevemk14ebr** [comment]
Awesome find thanks! Do you want to submit a PR to get yourself on the contributors list? Otherwise i can do the modification myself too.

**Comment by stevemk14ebr** [comment]
Fixed in 1b55739b36da1d00228d0ebb09121452260eb9c0
