### ISSUE TITLE
[zydis] Unit test failing in Release build mode

### ISSUE THREAD

**Issue by Randshot** [stevemk14ebr/PolyHook_2_0#35]
Hey, was playing with the **zydis** branch, and noticed that one of the unit tests is failing in **Release** build mode.

Here is some of the output I snipped:
```
[+] Info: Original function:
7ff693f93470 [3]: 0f 57 d2                      xorps xmm2, xmm2
7ff693f93473 [7]: 48 8d 0d f6 62 13 00          lea rcx, [rip + 0x1362f6] -> 7ff6940c9770
7ff693f9347a [4]: f3 0f 5a d0                   cvtss2sd xmm2, xmm0
7ff693f9347e [8]: f3 0f 58 05 22 65 13 00       addss xmm0, dword ptr [rip + 0x136522] -> 7ff6940c99a8
7ff693f93486 [3]: 0f 57 c9                      xorps xmm1, xmm1
7ff693f93489 [5]: 66 49 0f 7e d0                movq r8, xmm2
7ff693f9348e [4]: f3 0f 5a c8                   cvtss2sd xmm1, xmm0
7ff693f93492 [5]: 66 48 0f 7e ca                movq rdx, xmm1
7ff693f93497 [5]: e9 14 43 ff ff                jmp 0x7ff693f877b0 -> 7ff693f877b0
7ff693f9349c [1]: cc                            int3
7ff693f9349d [1]: cc                            int3
7ff693f9349e [1]: cc                            int3
7ff693f9349f [1]: cc                            int3
7ff693f934a0 [8]: c7 44 24 08 01 00 00 00       mov dword ptr [rsp + 8], 1
7ff693f934a8 [5]: 44 8b 44 24 08                mov r8d, dword ptr [rsp + 8]
7ff693f934ad [4]: 4c 8b 0c 24                   mov r9, qword ptr [rsp]
7ff693f934b1 [3]: 44 03 c1                      add r8d, ecx
7ff693f934b4 [4]: 8b 54 24 08                   mov edx, dword ptr [rsp + 8]
7ff693f934b8 [7]: 48 8d 0d a1 62 13 00          lea rcx, [rip + 0x1362a1] -> 7ff6940c9760
7ff693f934bf [5]: e9 ec 42 ff ff                jmp 0x7ff693f877b0 -> 7ff693f877b0
7ff693f934c4 [1]: cc                            int3
7ff693f934c5 [1]: cc                            int3
7ff693f934c6 [1]: cc                            int3
7ff693f934c7 [1]: cc                            int3
7ff693f934c8 [1]: cc                            int3
7ff693f934c9 [1]: cc                            int3
7ff693f934ca [1]: cc                            int3
7ff693f934cb [1]: cc                            int3
7ff693f934cc [1]: cc                            int3
7ff693f934cd [1]: cc                            int3
7ff693f934ce [1]: cc                            int3
7ff693f934cf [1]: cc                            int3
7ff693f934d0 [4]: 48 83 ec 48                   sub rsp, 0x48


[+] Info: Prologue to overwrite:
7ff693f93470 [3]: 0f 57 d2                      xorps xmm2, xmm2
7ff693f93473 [7]: 48 8d 0d f6 62 13 00          lea rcx, [rip + 0x1362f6] -> 7ff6940c9770
7ff693f9347a [4]: f3 0f 5a d0                   cvtss2sd xmm2, xmm0
7ff693f9347e [8]: f3 0f 58 05 22 65 13 00       addss xmm0, dword ptr [rip + 0x136522] -> 7ff6940c99a8


[!] Error: Cannot fixup IP relative data operation, needed disp. beyond max disp range: lea rcx, [rip + 0x1362f6] needed: 0x00007dc53f591820 raw: 0xffff823ac0a6e7e0 max: 0x000000007fffffff

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PolyHook_2.exe is a Catch v2.6.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
Minimal ILCallback
  Floating argument
-------------------------------------------------------------------------------
..\UnitTests\TestDetourNoTDx64.cpp(99)
...............................................................................

..\UnitTests\TestDetourNoTDx64.cpp(105): FAILED:
  REQUIRE( detour.hook() == true )
with expansion:
  false == true

===============================================================================
test cases:  19 |  18 passed | 1 failed
assertions: 974 | 973 passed | 1 failed
```

Note that this does not happen with **Debug** builds.
Here are the commands I used to configure and build PolyHook:
```
cd PolyHook_2_-
mkdir build
cd build
cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
.\PolyHook_2.exe
```

**Comment by stevemk14ebr** [comment]
The problem is this, it's not related to the zydis branch but just a case of how this particular build generated the asm and how the allocation went at runtime:

> 
> [!] Error: Cannot fixup IP relative data operation, needed disp. beyond max disp range: 
> lea rcx, [rip + 0x1362f6] needed: 0x00007dc53f591820 raw: 0xffff823ac0a6e7e0 max: 0x000000007fffffff
> 

this instruction is RIP relative, and only has 32bits of displacement available. It looks like the trampoline allocation was way farther away than 32bits, so the offset could not be re-encoded properly at the new location. This is unfortunately expected to occur in some edge cases, the only way to really fix this is to truly JIT equivalent assembly instead of just relocating the original but thats really hard and i punted on that.

https://github.com/stevemk14ebr/PolyHook_2_0/issues/14

I appreciate you testing this branch, i wrote it really fast! If you find any more issues, or are confident that it's stable i'd love to hear. I'd really like to make zydis the master and capstone the alt branch but i didn't have enough time to be confident in it.

**Comment by Randshot** [comment]
Ah, understood. Forgot to search closed issues before creating this one.
Btw, how do other hooking libraries (like MinHook) solve this, if they do at all.

**Comment by stevemk14ebr** [comment]
No worries. Most libraries do not solve this, I know minhook will fail silently (it's really bad don't use it). Not sure about MS detours. There's alot of edge cases I worked out, and chose to fail if not fixable, I give stronger guarantees than most libraries do. 

I know there is a library that actually rewrites the entire function by re-writing the function of interest entirely into little blocks and injecting the hook code as just another block. But this was against my design goal of minimizing the re-arite surface so as to be harder to detect

**Comment by Randshot** [comment]
OK. Gotcha.
