### ISSUE TITLE
HWBreakPointHook doesn't work but BreakPointHook does?

### ISSUE THREAD

**Issue by gir489** [stevemk14ebr/PolyHook_2_0#42]
I'm trying to hook two functions with a breakpoint because detours are detected.

When using BreakPointHook it seems to work for a while, but the detection eventually spots it.  Here's the code I'm using:

`m_send_network_hook = std::make_shared<PLH::HWBreakPointHook>((char*)g_pointers->m_send_network_event_function, (char*)&hooks::send_network_event_hook);
m_anti_cheat_hook = std::make_shared<PLH::HWBreakPointHook>((char*)g_pointers->m_anti_cheat_function, (char*)&hooks::anti_cheat_function_hook);`

The hook() method returns true, which I means it found a HW breakpoint slot to use. If I change it to PLH::BreakPointHook it works fine. Any ideas?

EDIT: I see BreakPointHook just writes 0xCC (INT3) to the function, and waits for the exception via VEH. That won't work since the function is hashed by the anti-cheat.

EDIT2: Is it because only the caller gets the exception? I thought that because Cheat Engine uses Hardware Breakpoints for debugging, it could be used as a hook. Is there no way to hook something you're not directly calling? Seems pointless to have a hook on something you're calling, you'd want a hook on something someone else is calling...

**Comment by stevemk14ebr** [comment]
Hmm it should work, it's possible they hook SetThreadContext themselves to disable this method? Can you verify if the top level VEH is ever called https://github.com/stevemk14ebr/PolyHook_2_0/blob/76cd66675c8107af85fcf01f98ca1d68a443a62c/sources/AVehHook.cpp#L33? Additionally if you can attach a debugger and see if the debug registers are changed properly. You might be able to get away with an EAT hook on the actual network API they use, not many games protect their exports.

**Comment by gir489** [comment]
The game doesn't use SetThreadContext. I was able to resolve SetThreadContext via the EAT from KERNEL32.DLL and it pointed to the right place. This game doesn't have any exports.

Well this sucks... I guess they've really thought of everything. I can't find a single way to hook this without the detecting spotting it...

**Comment by stevemk14ebr** [comment]
Read my edit about HWBPS's. And i mean to EAT hook send() and recv()

**Comment by gir489** [comment]
I tried a PAGE_GUARD hook, and it was so slow, it dropped my FPS in half. You gave me an idea though, I'm going to use the detour hook to setup the hardware breakpoint hook, since that should be in the same thread as the game's caller thread, then unhook the detour. That should be in such a short enough time, it doesn't trigger the anti cheat.

**Comment by gir489** [comment]
So that seems to work great, except when I uninject the cheat, the library is saying it's unhooked, but I'm crashing at about the same time the hardware breakpoint should be called... I can't figure out why, because I'm calling unHook on it and it's returning true from it... It's crashing at some random place after the module has completed....

**Comment by stevemk14ebr** [comment]
If you're still getting a single_step exception then the breakpoint wasn't uninstalled successfully. Why that happened i don't know, probably some issue you are doing with the thread stuff. There's no reason you need to stack the HWBP hook on top of a detour, just modify the library to not call GetCurrentThread() anywhere in HWBP and instead have it get the HANDLE of whatever calling thread you want to hook everytime. Also don't manually call the destructors, according to your code above you are using a shared_ptr which will destruct it for you when you reset it.

You will probably need to debug this yourself, hooking is hard. Idk what you mean about two calls that is not correct, the inteded flow is m_anti_cheat_function() -> HWBP hit -> AVEH::Handler -> HWBP::Handler -> your hook callback -> m_anti_cheat_function -> HWBP restored by protection object -> ... repeat

Protection object:
https://github.com/stevemk14ebr/PolyHook_2_0/blob/76cd66675c8107af85fcf01f98ca1d68a443a62c/UnitTests/TestHWBreakpointHook.cpp#L22

**Comment by gir489** [comment]
I think this is just dancing around the fire instead of putting the fire out. I'm going to try attacking the anti-cheat directly instead of trying to avoid it... Seems much simpler, and only getting one thread from the anti-cheat that's called from 6 different threads, it's definitely not going to work. 

What I mean by having two hooks was:

1. Create a detour on the function I'm hooking.
2. When the detour is called, remove the detour, create a hardware breakpoint from this detour, as it should be from within the game's thread.
3. Store the current thread as a member.

**Comment by stevemk14ebr** [comment]
Yes i understand that's how you were using the hook, you don't need to do that. Just get the thread id's you care about and modify the library to lookup the threads HANDLES you want and set a breakpoint on each of those. You can go lower level and hook the apis the anti-cheat is using if you can't hook that function.
