### ISSUE TITLE
How to use this with ExternalProject_Add?

### ISSUE THREAD

**Issue by steamp0rt** [stevemk14ebr/PolyHook_2_0#48]
What title says

```
include(ExternalProject)
ExternalProject_Add(polyhook
    GIT_REPOSITORY https://github.com/stevemk14ebr/PolyHook_2_0
    GIT_TAG "00709c8621af8a6f9e91200088178e6d9f751097"
    INSTALL_COMMAND ""
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/external/polyhook
)
```

I can't seem to find a way to include the include dirs and link the outputted libs. No matter what I do, VS always puts the .lib in a Debug/Release folder.

**Comment by stevemk14ebr** [comment]
I'm not sure. If you look at my example project you'll see it just points to the already build libraries. If I were you I'd just copy my example project and add a build script that fired polyhook first then youra

**Comment by steamp0rt** [comment]
k
