### ISSUE TITLE
[Question] How to detect some HOOKs?

### ISSUE THREAD

**Issue by SourcePowered** [stevemk14ebr/PolyHook_2_0#55]
I really have no clue how to write this code.  (Not good at learning...)
I want to use Capstone to implement a HOOK detection (to check if a particular function has an wrong jmp or others).
For example, if I want to check if GetCommandLineW is HOOK, what should I do? I tried a few methods, but it didn't seem to work. Going deeper, it was beyond the control of my brain.
So I can only come for help. Maybe you can give me some sample code ... or some tips. Thank you very much.

**Comment by stevemk14ebr** [comment]
sorry, perhaps you should get control of your brain and get better at learning first. That's my tip.
