### ISSUE TITLE
Relocate strange 32bit EIP relative addressing

### ISSUE THREAD

**Issue by vcid** [stevemk14ebr/PolyHook_2_0#6]
Hello Stevenmk14ebr, very nice library you have here. I have been using PolyHook 1.0 as a reference to enhance my memory leak detection library which hooks malloc/calloc/realloc/free. I was using your code to help write my own routines which perform the ASM relocation of the trampoline code (up till now I was using hardcoded trampolines).

In Linux32 when hooking Malloc the first instructions of the function are:
```
   0xf7e70df0 <malloc>:         push   esi  
   0xf7e70df1 <malloc+1>:       push   ebx  
   0xf7e70df2 <malloc+2>:       call   0xf7f2102b  
   0xf7e70df7 <malloc+7>:       add    ebx,0x134209  
   0xf7e70dfd <malloc+13>:      sub    esp,0x14  
   0xf7e70e00 <malloc+16>:      mov    eax,DWORD PTR [ebx-0xa4]  
```

The function at `0xf7f2102b` is actually just a function that puts EIP into EBX:
```
   0xf7f2102b:  mov    ebx,DWORD PTR [esp]
   0xf7f2102e:  ret    
```

So malloc is actually grabbing an object relative to EIP -- but it's done through calling a function that moves EIP into the EBX register and then addressing relative to EBX.

The code from PolyHook 1.0 obviously didn't handle this as it only adjusted explicit EIP/RIP relative addressing, I haven't been able to test PolyHook 2.0 but it looks like it might have the same issue.

Originally I was using a hand-crafted trampoline which explicitly placed the object in question into EBX, but if I want to dynamically generate the trampoline I obviously cannot do that anymore.

Do you know of any way around this issue? Or maybe I'm just stupid and PolyHook 2.0 handles this elegantly and I'm just missing it?

**Comment by vcid** [comment]
Yeah... I thought so. Thanks for the input, cheers from UC ;)

**Comment by stevemk14ebr** [comment]
I've been working on asmjit integration to make callback code generatable at runtime, https://github.com/stevemk14ebr/PolyHook_2_0/blob/inlineNOtypedef/sources/ILCallback.cpp#L14. This may help you, your specific use case is a little more lower level than the abstraction im introducing, but you can gut this where i linked and just emit your callback to do your mov into ebx as first line. This isn't done at all yet and only works on x64 for now, but it might help.

**Comment by vcid** [comment]
I actually made a small hack which would detect functions which simply place EIP into a register after which I could update relocations for that register -- I don't really see any further emulation being necessary because this is just a ghetto 32bit workaround for inability to do direct RIP relative addressing.

```
static bool __detect_ip_retrieval(cs_insn *curins, uintptr_t from, uintptr_t to, x86_reg *fixup_reg)
{
    cs_insn *instructioninfo;
    if (!curins) {
        return false;
    }
    cs_x86 *x86 = &(curins->detail->x86);
    cs_x86_op *op = &(x86->operands[0]);
    off_t offset = (to - from);
    size_t instructioncount = cs_disasm(capstone_handle, op->imm - offset, 16, (uintptr_t)op->imm - offset, 0, &instructioninfo);
    size_t i = 0;
    size_t j = 0;

    if (instructioncount < 2) {
        return false;
    }

#ifdef _X64
#define SP_REG X86_REG_RSP
#else
#define SP_REG X86_REG_ESP
#endif

    cs_x86 *op1 = &(instructioninfo[0].detail->x86);
    cs_x86 *op2 = &(instructioninfo[1].detail->x86);

    if (op1->op_count != 2) {
        return false;
    }
    if (op1->operands[0].type != X86_OP_REG) {
        return false;
    }
    if (op1->operands[1].type != X86_OP_MEM) {
        return false;
    }
    if (op1->operands[1].mem.base != SP_REG) {
        return false;
    }
    if (op1->operands[1].mem.scale != 1) {
        return false;
    }
    if (op1->operands[1].mem.disp != 0) {
        return false;
    }

    // the register that is the destination of esp/rsp
    if (fixup_reg) {
        *fixup_reg = op1->operands[0].reg;
    }

    return true;
}
```
