### ISSUE TITLE
Analog hook in polyhook 2.0

### ISSUE THREAD

**Issue by continue98** [stevemk14ebr/PolyHook_2_0#69]
Hi, is there a similar hook in polyhook?

https://github.com/sr-tream/ClassicArrow/blob/master/ccallhook.cpp#L3-L48

**Comment by stevemk14ebr** [comment]
That's an 0xE9 style inline hook for x86. This is called an inline hook or a detour and yes it's supported.

**Comment by continue98** [comment]
I am use polyhook and crash game. (the code is exactly the same as in CCallHook)

https://github.com/sr-tream/ClassicArrow/blob/master/main.cpp#L31-L32

polyhook code: 
`
uint64_t hookPrintfTramp = NULL;
`
`
        PLH::CapstoneDisassembler dis(PLH::Mode::x86);
        PLH::x86Detour detour((char*)0x00748DA3, (char*)&MainLoop, &hookPrintfTramp, dis);
        detour.hook();
`
`
void CALLBACK MainLoop()
{
    
}
`

P.S: the function is even called 1 time, but then it crashes. 
P.S.S: I am confused that there is 6 used in the constructor

I hope you can help

**Comment by stevemk14ebr** [comment]
debug it
