### ISSUE TITLE
HWBP PLH::HWBreakPointHook::HWBreakPointHook': no overloaded function takes 2 arguments

### ISSUE THREAD

**Issue by LeimonDust** [stevemk14ebr/PolyHook_2_0#71]
Error	C2661	'PLH::HWBreakPointHook::HWBreakPointHook': no overloaded function takes 2 arguments

hwBpHook = std::make_shared<PLH::HWBreakPointHook>((char*)&hookMeCallbackHWBP, (char*)&hookMeCallbackHWBP);

**Comment by stevemk14ebr** [comment]
The error is what it says, there's no function accepting 2 args:  https://github.com/stevemk14ebr/PolyHook_2_0/blob/7f985a66e0e5f1a9529b759d4d4b2d265869fb7a/sources/HWBreakPointHook.cpp#L12

You need to pass a handle to which thread you want to hook on since hwbps are thread local

**Comment by LeimonDust** [comment]
Error	LNK2001	unresolved external symbol "public: __thiscall PLH::HWBreakPointHook::HWBreakPointHook(char const *,char const *,void *)" (??0HWBreakPointHook@PLH@@QAE@PBD0PAX@Z)

hwBpHook = std::make_shared<PLH::HWBreakPointHook>((char*)&hookMeHWBP, (char*)&hookMeCallbackHWBP, GetCurrentThread());

	
Please, update your https://github.com/stevemk14ebr/PolyHook_2_0/blob/master/UnitTests/TestHWBreakpointHook.cpp

**Comment by stevemk14ebr** [comment]
I would appreciate a PR

**Comment by LeimonDust** [comment]
I can't make it work anyway

Error LNK2001 unresolved external symbol "public: __thiscall PLH::HWBreakPointHook::HWBreakPointHook(char const *,char const *,void *)" (??0HWBreakPointHook@PLH@@QAE@PBD0PAX@Z)

Code:
hwBpHook = std::make_sharedPLH::HWBreakPointHook((char*)&hookMeHWBP, (char*)&hookMeCallbackHWBP, GetCurrentThread());

**Comment by stevemk14ebr** [comment]
verify this is ON : https://github.com/stevemk14ebr/PolyHook_2_0/blob/7f985a66e0e5f1a9529b759d4d4b2d265869fb7a/CMakeLists.txt#L10. You're linking improperly

**Comment by LeimonDust** [comment]
HWBreakpoint does it work at all?
This does not pass the test, error _Exception thrown at 0x77027065 (ntdll.dll) in PolyHook_2.exe: 0xC0000005: Access violation writing location 0x006E0FD8.
_
`//
// Created by steve on 7/9/18.
//
#include <memory>

#include <Catch.hpp>

#include "polyhook2/Exceptions/HWBreakPointHook.hpp"
#include "polyhook2/tests/TestEffectTracker.hpp"

EffectTracker effects3;

NOINLINE int hookMeHWBP() {
	volatile int i = 0;
	i += 1;
	i += 2;
	return i;
}

std::shared_ptr<PLH::HWBreakPointHook> hwBpHook; // must be ptr because we need to call getProtectionObject
NOINLINE int hookMeCallbackHWBP() {
	auto protObj = hwBpHook->getProtectionObject();
	volatile int i = 0;
	i += 1;

	effects3.PeakEffect().trigger();
	return hookMeHWBP(); // just call original yourself now
}

TEST_CASE("Testing Hardware Breakpoints", "[AVehHook],[HWBreakPointHook]") {
	SECTION("Verify callback is executed") {
		hwBpHook = std::make_shared<PLH::HWBreakPointHook>((char*)&hookMeHWBP, (char*)&hookMeCallbackHWBP, GetCurrentThread());
		REQUIRE(hwBpHook->hook() == true);

		effects3.PushEffect();
		REQUIRE(hookMeHWBP() == 3);
		REQUIRE(effects3.PopEffect().didExecute());
		hwBpHook->unHook();
		hwBpHook.reset();
	}

	SECTION("Verify multiple calls in a row reprotect") {
		hwBpHook = std::make_shared<PLH::HWBreakPointHook>((char*)&hookMeHWBP, (char*)&hookMeCallbackHWBP, GetCurrentThread());
		REQUIRE(hwBpHook->hook() == true);

		effects3.PushEffect();
		REQUIRE(hookMeHWBP() == 3);
		REQUIRE(effects3.PopEffect().didExecute());

		effects3.PushEffect();
		REQUIRE(hookMeHWBP() == 3);
		REQUIRE(effects3.PopEffect().didExecute());

		effects3.PushEffect();
		REQUIRE(hookMeHWBP() == 3);
		REQUIRE(effects3.PopEffect().didExecute());
		hwBpHook->unHook();
	}
}`

**Comment by stevemk14ebr** [comment]
it worked last time i looked at it. The tests may not be run under a debugger, verify you are not doing that. If that's not the issue then you will have to debug it, i will only fix bugs where proper details are given, there is not enough info here.
