### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by StebX** [stevemk14ebr/PolyHook_2_0#72]
My game crashes when I load my dll. I tried using PageGuard hook using other lib and it works but it makes the game very slow. Now im trying to use polyhook’s breakpoint.

`#include <windows.h>
#include "polyhook/include/polyhook2/Exceptions/AVehHook.hpp"
#include "polyhook/include/polyhook2/Exceptions/BreakPointHook.hpp"
#include "polyhook/include/polyhook2/Exceptions/HWBreakPointHook.hpp"
#include "polyhook/include/polyhook2/TestEffectTracker.hpp"
#include <memory>

#pragma comment(lib, "polyhook/lib/PolyHook_2.lib")

DWORD norecoil = 0x00853B30;
DWORD jmpnorecoil = 0x00853B35;

float ChingCho = 0;

std::shared_ptr<PLH::BreakPointHook> BPHook;
EffectTracker effects3;

using namespace std;

_declspec (naked) NOINLINE int Kongchi()
{
    printf("Nodelay Activated.. \n");
    _asm
    {
        movss xmm0, ChingCho
        movss[esi + 0x58], xmm0
        jmp jmpNDL2
    }
}

NOINLINE int HookCallBackHWBP()
{
    auto protObj = BPHook->getProtectionObject();
    //effects3.PeakEffect().trigger();
    return Kongchi();
}

DWORD WINAPI STEB(HMODULE hModule)
{
    BPHook = std::make_shared<PLH::BreakPointHook>((uint32_t)norecoil, (uint32_t)HookCallBackHWBP);
    cout << "Preparing" << endl;
    BPHook->hook();
    cout << "Hooked" << endl;
    return 1;
}

BOOL WINAPI DllMain(HMODULE hModule, DWORD dwReason, LPVOID lpReserved)
{
    if (dwReason == DLL_PROCESS_ATTACH)
    {
        DisableThreadLibraryCalls(hModule);

        AllocConsole();

        FILE* fDummy;
        freopen_s(&fDummy, "CONOUT$", "w", stdout);
        freopen_s(&fDummy, "CONOUT$", "w", stderr);
        freopen_s(&fDummy, "CONIN$", "r", stdin);

        CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)STEB, NULL, 0, NULL);
    }
    return TRUE;
}  `

**Comment by stevemk14ebr** [comment]
you need to debug the crash

**Comment by StebX** [comment]
> you need to debug the crash

Crashes here BPHook = std::make_sharedPLH::BreakPointHook((uint32_t)norecoil, (uint32_t)HookCallBackHWBP);

**Comment by stevemk14ebr** [comment]
not enough information
