### ISSUE TITLE
hooking internetConnectW problem

### ISSUE THREAD

**Issue by SpenserCai** [stevemk14ebr/PolyHook_2_0#78]
I use it hook internetConnectW bug have some problem
// ExampleProject.cpp : Defines the entry point for the application.
//

#include <iostream>
#include <windows.h>
#include <Wininet.h>
#include <string>
#include "polyhook2/CapstoneDisassembler.hpp"
#include "polyhook2/Detour/x64Detour.hpp"
#include "polyhook2/PE/IATHook.hpp"
using std::string;
using namespace std;
#pragma comment(lib,"asmjit.lib")
#pragma comment(lib,"capstone.lib")
#pragma comment(lib,"PolyHook_2.lib")
#pragma comment(lib,"Zycore.lib")
#pragma comment(lib,"Zydis.lib")

#include <cstdarg>

string WCharToMByte(LPCWSTR lpcwszStr)
{
	string str;
	DWORD dwMinSize = 0;
	LPSTR lpszStr = NULL;
	dwMinSize = WideCharToMultiByte(CP_OEMCP, NULL, lpcwszStr, -1, NULL, 0, NULL, FALSE);
	if (0 == dwMinSize)
	{
		return FALSE;
	}
	lpszStr = new char[dwMinSize];
	WideCharToMultiByte(CP_OEMCP, NULL, lpcwszStr, -1, lpszStr, dwMinSize, NULL, FALSE);
	str = lpszStr;
	delete[] lpszStr;
	return str;
}

typedef HINTERNET(WINAPI *tInternetConnectWFunc)
(
	HINTERNET     hInternet,
	LPCWSTR       lpszServerName,
	INTERNET_PORT nServerPort,
	LPCWSTR       lpszUserName,
	LPCWSTR       lpszPassword,
	DWORD         dwService,
	DWORD         dwFlags,
	DWORD_PTR     dwContext
);

//tInternetConnectWFunc oInternetConnectW;
tInternetConnectWFunc oInterConnectWFunc;

uint64_t oInternetConnectW;

uint64_t oGetCurrentThreadID;

NOINLINE DWORD __stdcall hkGetCurrentThreadId() {
	return 0;
}

HINTERNET WINAPI hkInternetConnectW(
	HINTERNET hInternet,
    LPCWSTR lpszServerName,
	INTERNET_PORT nServerPort,
    LPCWSTR lpszUserName,
	LPCWSTR lpszPassword,
	DWORD dwService,
	DWORD dwFlags,
	DWORD_PTR dwContext
)
{
	LPCWSTR url = lpszServerName;
	MessageBox(NULL, L"I'm alive!", L"Hello", 0);
	if (WCharToMByte(url).find("baidu.com") >= 0)
	{
		url = L"www.sogou.com";
	}
	
	oInterConnectWFunc(hInternet, url, nServerPort, lpszUserName, lpszPassword, dwService, dwFlags, dwContext);
}

PLH::CapstoneDisassembler dis(PLH::Mode::x64);
//PLH::IatHook hook("kernel32.dll", "GetCurrentThreadId", (char*)&hkGetCurrentThreadId, (uint64_t*)&oGetCurrentThreadID, L"");
PLH::IatHook hook("wininet.dll", "InternetConnectW", (uint64_t)&hkInternetConnectW, (uint64_t*)&oInterConnectWFunc, L"");

BOOL APIENTRY DllMain(HMODULE hModule,
	DWORD  ul_reason_for_call,
	LPVOID lpReserved
)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
	{
		MessageBox(NULL, L"IN HOOK", L"HOOK", 0);
		if (hook.hook() == true) {
			MessageBox(NULL, L"hook success", L"HOOKED", 0);
			//std::cout << "hook success." << std::endl;
		}
		else
		{
			MessageBox(NULL, L"hook error", L"HOOKED", 0);
		}
		
	}
	break;
	case DLL_PROCESS_DETACH:
		hook.unHook();
		break;
	}
	return TRUE;
}

hook error I dont know why

**Comment by stevemk14ebr** [comment]
Use the logging interfaces to setup logging and post the assembly output

**Comment by SpenserCai** [comment]
how can I use log thank you

**Comment by stevemk14ebr** [comment]
https://github.com/stevemk14ebr/PolyHook_2_0/blob/master/sources/ErrorLog.cpp
