### ISSUE TITLE
hook ntdll

### ISSUE THREAD

**Issue by SpenserCai** [stevemk14ebr/PolyHook_2_0#79]
if use this way get address can I hook it?

typedef DWORD(__stdcall *pNtTerminateProcess)(HANDLE, UINT);
pNtTerminateProcess fnNtTerminateProcess = (pNtTerminateProcess)GetProcAddress(GetModuleHandle(TEXT("ntdll.dll")), "NtTerminateProcess");

my code:

typedef NTSTATUS(WINAPI *tNtTerminateProcess)
(
	HANDLE   ProcessHandle,
	NTSTATUS ExitStatus
);
tNtTerminateProcess oNtTerminateProcessFunc;
NTSTATUS WINAPI hkNtTerminateProcess(HANDLE ProcessHandle,NTSTATUS ExitStatus)
{
	printf("11111");
	MessageBox(NULL, L"I'm alive!", L"Hello", 0);
	return 0;
}
PLH::IatHook hook("ntdll.dll", "NtTerminateProcess", (uint64_t)&hkNtTerminateProcess, (uint64_t*)&oNtTerminateProcessFunc, L"NtTerminateProcess");

**Comment by stevemk14ebr** [comment]
Please report bugs on the issue tracker and questions in the Gitter community chat linked in the projects readme. For an example of IatHook (and all other hook types) please refer to the UnitTests until i complete the documentation. https://github.com/stevemk14ebr/PolyHook_2_0/blob/731008adb2e12d6ecc31359c0cdb00f6714ca778/UnitTests/TestIatHook.cpp#L34

Afaik this should work fine.
