### ISSUE TITLE
Can I redesign the structure of the project catalog and optimize the complie script?

### ISSUE THREAD

**Issue by buzzers** [stevemk14ebr/PolyHook_2_0#8]
This is an excellent one in what I think is an open source hook library, but when I try to use it, I find that the project directory is confusing, and the complie script has some bugs on windows, can I reorganize and submit a PR?

**Comment by stevemk14ebr** [comment]
You may, and I appreciate it 😀. Make sure I can gen x86/x64
rel/Deb/relwdebinfo and I'll accept

**Comment by stevemk14ebr** [comment]
I was curious what changes you might have in mind?

**Comment by liuhan907** [comment]
No, nothing has changed, just from Monday to Friday, there's not much time to do it.

**Comment by stevemk14ebr** [comment]
👍 . If you do get some time please discuss ideas for changes with me first, that way we don't accidentally do work i might reject 😃

**Comment by buzzers** [comment]
No problem, of course I hope we can all put our time into effective work.
