### ISSUE TITLE
can i hook ntdll with polyhook2

### ISSUE THREAD

**Issue by SpenserCai** [stevemk14ebr/PolyHook_2_0#80]
I want hook taskmgr.exe's NtTerminateProcess, i don't why it's not work(messagebox show hook success)

typedef NTSTATUS(WINAPI *tNtTerminateProcess)
(
	HANDLE   ProcessHandle,
	NTSTATUS ExitStatus
);
tNtTerminateProcess oNtTerminateProcessFunc;
NTSTATUS WINAPI hkNtTerminateProcess(HANDLE ProcessHandle,NTSTATUS ExitStatus)
{
	//g_inlineHookObj7.UnHook();
	MessageBox(NULL, L"I'm alive!", L"Hello", 0);
	return oNtTerminateProcessFunc(ProcessHandle, ExitStatus);
}

void PolyHook2Hook()
{
	oNtTerminateProcessFunc = (tNtTerminateProcess)GetProcAddress(GetModuleHandle(TEXT("ntdll.dll")), "NtTerminateProcess");
	printf("123");
	PLH::IatHook hook("ntdll.dll", "NtTerminateProcess", (uint64_t)&hkNtTerminateProcess, (uint64_t*)&oNtTerminateProcessFunc, L"NtTerminateProcess");
	if (hook.hook() == true) {
		MessageBox(NULL, L"hook success", L"HOOKED", 0);
		std::cout << "hook success." << std::endl;
	}
	else
	{

		MessageBox(NULL, L"hook error", L"HOOKED", 0);
	}
}

BOOL APIENTRY DllMain(HMODULE hModule,
	DWORD  ul_reason_for_call,
	LPVOID lpReserved
)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
		PolyHook2Hook();
		//InlineHook();
		break;
	case DLL_THREAD_ATTACH:
	case DLL_THREAD_DETACH:
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

**Comment by stevemk14ebr** [comment]
You probably need to specify the module name you want to hook NtTerminateThread on: https://github.com/stevemk14ebr/PolyHook_2_0/blob/731008adb2e12d6ecc31359c0cdb00f6714ca778/sources/IatHook.cpp#L10 . Please only report bugs via the issue tracker this is _not_ the place to get help. Use a debugger to figure out what's going on or ask on gitter which is linked in this projects readme and hope that either somewhere there can find the time to help you or that i find time myself.
