### ISSUE TITLE
A compile error occurs when fetching headers that use "using namespace std :: placeholders;"

### ISSUE THREAD

**Issue by hiroki19990625** [stevemk14ebr/PolyHook_2_0#85]
Environment:  Windows10 Visual Studio 2019 Community

I succeeded in compiling by adding "#include <functional>", but I am having trouble because other users need to change the header when building.

**Comment by stevemk14ebr** [comment]
The source code builds fine without any additional includes. Ensure you opened the project correctly with cmake and have c++ 17 enabled.

**Comment by hiroki19990625** [comment]
solved.

The problem was that I was building with a dynamic link library project instead of a cmake project.

This library is very good Thank you.
