### ISSUE TITLE
x64detour placeholders not member of std

### ISSUE THREAD

**Issue by ross-weir** [stevemk14ebr/PolyHook_2_0#87]
I notice this was raised before here: https://github.com/stevemk14ebr/PolyHook_2_0/issues/85

I believe this is a bug, I cannot get a project using x64detour to build without first including `<functional>`. I can confirm the project is setup correctly and is using `c++17`.

The include was removed here: https://github.com/stevemk14ebr/PolyHook_2_0/commit/a467313fb406c0f9baf3cccbb334a8817c67c917#diff-40ff9b9e776492b722f585ee7ec75ff6e30e2db476ce0a9ca3eb3df69d4f038e

I believe tests still pass because `catch.hpp` happens to include `functional`, and it's included first here and in the other test file: https://github.com/stevemk14ebr/PolyHook_2_0/blob/fd7badbeace6d6d9ce4b9b7a42591842327398c5/UnitTests/TestDetourx64.cpp#L4

Thanks for the great library.

**Comment by stevemk14ebr** [comment]
what is your build process and how is polyhook integrated into your project, did you copy particular header files directly into your project or are you building polyhook as a library and linking it

**Comment by ross-weir** [comment]
Thanks for the response.

Exact errors:
```
'placeholders': a namespace with this name does not exist 
'placeholders': is not a member of 'std' 
```

I'm using cmake and polyhook is consumed as a subdirectory. I have not copied or moved header files, building as a static library and linking. My configuration is almost an exact copy of `ExampleProject` at the moment except added include paths and different lib paths given the slightly different directory structure.

**Comment by ross-weir** [comment]
Build fails:

```cpp
#include <Windows.h>
#include <iostream>
//#include <functional>
#include "polyhook2/Detour/x64Detour.hpp"
#include "polyhook2/CapstoneDisassembler.hpp"

FILE* std_handle;
PLH::x64Detour* handle_set_xp_detour;
PLH::x64Detour* handle_recv_pkt_detour;
PLH::CapstoneDisassembler dis(PLH::Mode::x64);

BOOL APIENTRY DllMain(HMODULE hModule,
    DWORD ul_reason_for_call,
    LPVOID lpReserved)
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
        DisableThreadLibraryCalls(hModule);
        AllocConsole();
        freopen_s(&std_handle, "conout$", "w", stdout);
        freopen_s(&std_handle, "conin$", "r", stdin);

        break;
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
```

Build succeeds:

```cpp
#include <Windows.h>
#include <iostream>
#include <functional>
#include "polyhook2/Detour/x64Detour.hpp"
#include "polyhook2/CapstoneDisassembler.hpp"

FILE* std_handle;
PLH::x64Detour* handle_set_xp_detour;
PLH::x64Detour* handle_recv_pkt_detour;
PLH::CapstoneDisassembler dis(PLH::Mode::x64);

BOOL APIENTRY DllMain(HMODULE hModule,
    DWORD ul_reason_for_call,
    LPVOID lpReserved)
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
        DisableThreadLibraryCalls(hModule);
        AllocConsole();
        freopen_s(&std_handle, "conout$", "w", stdout);
        freopen_s(&std_handle, "conin$", "r", stdin);

        break;
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
```

**Comment by stevemk14ebr** [comment]
Thanks for the report and PR. I believe this error is due to your project structure. Polyhook is designed to be built as a lib and then linked, rather than included as a subdirectory. Including it this way has likely messed up the include cycles. But of course this should be supported too, as headers should include all the dependencies they need directly, so I have merged the PR.
