### ISSUE TITLE
A question about expandProlSelfJmps

### ISSUE THREAD

**Issue by mavetek** [stevemk14ebr/PolyHook_2_0#89]
https://github.com/stevemk14ebr/PolyHook_2_0/blob/master/sources/ADetour.cpp
```
bool PLH::Detour::expandProlSelfJmps(insts_t& prol,
									 const insts_t& func,
									 uint64_t& minProlSz,
									 uint64_t& roundProlSz) {
	const uint64_t prolStart = prol.front().getAddress();
	branch_map_t branchMap = m_disasm.getBranchMap();

	for (size_t i = 0; i < prol.size(); i++) {
		auto inst = prol.at(i);

		// is there a jump pointing at the current instruction?
		if (branchMap.find(inst.getAddress()) == branchMap.end())
			continue;

		insts_t srcs = branchMap.at(inst.getAddress());
		uint64_t maxAddr = 0;
		for (const auto& src : srcs) {
			const uint64_t srcEndAddr = src.getAddress() + src.size();
			if (srcEndAddr > maxAddr)
				maxAddr = srcEndAddr;
		}

		minProlSz = maxAddr - prolStart;

		// expand prol by one entry size, may fail if prol too small
		auto prolOpt = calcNearestSz(func, minProlSz, roundProlSz);
		if (!prolOpt)
			return false;
		prol = *prolOpt;
	}

	return true;
}
```
Hello I have a question about this function.
My english is bad so I try to make a pseudo-example:
In this function what happens if:
prol[1] has a re-entrant jump at 0x22222222
prol[2] has a re-entrant jump at 0x11111111

when you are iterating prol[1] the minProlSz will be bigger than when iterating prol[2], but at the end of the loop minProlSz (and roundProlSz) will have the smaller size because prol[2] is the last of them and it just overrides it.
Can this happen or I'm missing something?

**Comment by stevemk14ebr** [comment]
Hi, I am not sure this would happen since we always check that the new address is greater than the old one:
```
const uint64_t srcEndAddr = src.getAddress() + src.size();
			if (srcEndAddr > maxAddr)
				maxAddr = srcEndAddr;
```

If i'm incorrect can you please put together a unit test here https://github.com/stevemk14ebr/PolyHook_2_0/blob/fcca66f5a35a92ebd9854dd5d30640313887248a/UnitTests/TestDetourx86.cpp#L136 to demonstrate?

**Comment by mavetek** [comment]
I'm talking about the external cycle:
```
for (size_t i = 0; i < prol.size(); i++)
```
At the end of every iteration there is:
```
minProlSz = maxAddr - prolStart;
auto prolOpt = calcNearestSz(func, minProlSz, roundProlSz);
if (!prolOpt)
	return false;
prol = *prolOpt;
```
So the prologue and size gets re-setted every iteration and it takes for granted that the last iteration its the biggest prologue.
To be fair I didn't debug the project yet, I'm just esamining the code and trying to visualize mentally.
This is what I see in my mind, what happens in this situation?
![example](https://user-images.githubusercontent.com/11120463/103134122-1cb86600-46af-11eb-9d81-bdf41603f1bb.png)
I'm probably missing something here, I don't know.
Anyway if its not clear, when I have more time I'll try to test it.
Feel free to close it.

**Comment by stevemk14ebr** [comment]
Oh you may be correct actually, i think i made a mistake putthing the maxAddr variable into the loop. Instead this line should be outside the loop: https://github.com/stevemk14ebr/PolyHook_2_0/blob/21398181fe02db6213c54ea58c332579e8169996/sources/ADetour.cpp#L112

**Comment by stevemk14ebr** [comment]
Thank you for reporting this! I have commited this patch: https://github.com/stevemk14ebr/PolyHook_2_0/commit/84d6be2a208fa7ab9d14e27c497413d598632770

Do you agree with me that this will fix the issue?

**Comment by mavetek** [comment]
Looks fine.
Nice code btw, I like the way you write, its easy to follow and remember.

**Comment by stevemk14ebr** [comment]
change goes live when this is merged: 
https://github.com/microsoft/vcpkg/pull/15537
