### ISSUE TITLE
Polyhook2 crashes on insts vector

### ISSUE THREAD

**Issue by m3chanical** [stevemk14ebr/PolyHook_2_0#94]
When returning from main and with a logger set up, Polyhook2 will cause a crash which seems to originate from the PLH::Instruction vector.

I am building a 64 bit app that hooks LoadLibraryExW and I have built the 64 bit version of PLH which is linked against this app. It seems to occur with both Zydis and Capstone. I pasted my code from the project below, and the repo is here: https://github.com/m3chanical/LoadLibraryHook

I'm on Win 10 with 64gb ram and a Ryzen 5 2600. I'm building this within Visual Studio 2019 with the cmake project type.

In particular, the crashes will occur in two situations: 
1. With the logger, it'll crash when it outputs the Original Function text during the hook
2. With no logging, it'll crash on return from main with a stacktrace 

Here's a link to a pair of screenshots with the call stack from VS: https://imgur.com/a/AZimbEo

I'm not sure if these are two separate problems I'm having, but they both seem to be related to the instruction vector. I'm in the process of troubleshooting it, but I figured I'd create an issue in case there's something obvious I'm missing or something. I looked through the previous issues and didn't see anything related.

```cpp
// LoadLibraryHook.cpp : Defines the entry point for the application.
//

#include <Windows.h>
#include <LoadLibraryHook.h>
#include <polyhook2/ZydisDisassembler.hpp>
#include <polyhook2/Detour/x64Detour.hpp>

#include <cstdarg>
#include <conio.h>

uint64_t hookLoadLibrary = NULL; // original LoadLibrary
// IDA: LoadLibraryExW(LPCWSTR lpLibFileName, HANDLE hFile, DWORD dwFlags)
HMODULE WINAPI hk_LoadLibrary(LPCWSTR lpLibFileName, HANDLE hfile, DWORD dwFlags)
{
	printf("Loading file: %ws\n", lpLibFileName);
	return PLH::FnCast(hookLoadLibrary, &LoadLibraryExW)(lpLibFileName, hfile, dwFlags);
}

int getch_noblock()
{
	if (_kbhit())
		return _getch();
	return -1;
}

int main()
{
	auto error_log = std::make_shared<PLH::ErrorLog>();
	PLH::Log::registerLogger(error_log);
	PLH::ZydisDisassembler dis(PLH::Mode::x64);

	HMODULE k32 = GetModuleHandle("kernelbase.dll");
	if (k32 == NULL)
		return 0;
	// all of the loadlibrary functions in kernel32/kernelbase end up calling LoadLibraryExW, which is the last step before ntdll.
	auto load_lib_addr = GetProcAddress(k32, "LoadLibraryExW");
	if (load_lib_addr == NULL)
		return 0;
	printf("LoadLibraryExW address in kernelbase.dll: %p\n", load_lib_addr);
	
	PLH::x64Detour loadlib_detour(reinterpret_cast<uint64_t>(load_lib_addr), reinterpret_cast<uint64_t>(&hk_LoadLibrary), &hookLoadLibrary, dis);	
	
	loadlib_detour.hook();
	
	LoadLibraryA("F:\\vs_projects\\test_inject\\x64\\Debug\\test_inject.dll");

	while (true)
	{
		if (getch_noblock() != -1)
			break;
	}
	
	loadlib_detour.unHook();
	
	return 0;	
}
```

**Comment by stevemk14ebr** [comment]
Hey, I cannot reproduce this. I've modified your example a little, it's possible your injected DLL is causing corruption, try it with a system DLL that's already loaded. Also, no need for the getch_noblock thing, just use getchar()
```
#include <Windows.h>
#include <polyhook2/ZydisDisassembler.hpp>
#include <polyhook2/Detour/x64Detour.hpp>

#include <cstdarg>
#include <conio.h>

uint64_t hookLoadLibrary = NULL; // original LoadLibrary
// IDA: LoadLibraryExW(LPCWSTR lpLibFileName, HANDLE hFile, DWORD dwFlags)
HMODULE WINAPI hk_LoadLibrary(LPCWSTR lpLibFileName, HANDLE hfile, DWORD dwFlags)
{
	printf("Loading file: %ws\n", lpLibFileName);
	return PLH::FnCast(hookLoadLibrary, &LoadLibraryExW)(lpLibFileName, hfile, dwFlags);
}

int main()
{
	auto error_log = std::make_shared<PLH::ErrorLog>();
	PLH::Log::registerLogger(error_log);
	PLH::ZydisDisassembler dis(PLH::Mode::x64);

	HMODULE k32 = GetModuleHandleA("kernelbase.dll");
	if (k32 == NULL)
		return 0;
	// all of the loadlibrary functions in kernel32/kernelbase end up calling LoadLibraryExW, which is the last step before ntdll.
	auto load_lib_addr = GetProcAddress(k32, "LoadLibraryExW");
	if (load_lib_addr == NULL)
		return 0;
	printf("LoadLibraryExW address in kernelbase.dll: %p\n", load_lib_addr);
	
	PLH::x64Detour loadlib_detour(reinterpret_cast<uint64_t>(load_lib_addr), reinterpret_cast<uint64_t>(&hk_LoadLibrary), &hookLoadLibrary, dis);	
	
	loadlib_detour.hook();
	
	LoadLibraryExW(L"kernel32.dll", 0, 0);

	while (true)
	{
		if (getchar())
			break;
	}
	
	loadlib_detour.unHook();
	
	return 0;	
}
```

**Comment by stevemk14ebr** [comment]
Try the vcpkg installation instead, you may have linking or header
incompatibilities

**Comment by m3chanical** [comment]
Alright I installed PLH using vcpkg (I followed the guy who found the veh issue's code) and modified my build accordingly, and now it doesn't crash at all and seems like it's working pretty nicely. 

I suspect I may have screwed up the Zydis build or something. Maybe I can indeed re-build all this and see what I missed. 

Thank for the help!
