### ISSUE TITLE
code-cave too small issue

### ISSUE THREAD

**Issue by randydu** [stevemk14ebr/PolyHook_2_0#98]
When running release version of PolyHook2_2.exe on Win10/x64, it crashes on section:

https://github.com/stevemk14ebr/PolyHook_2_0/blob/146c97eb5694201701b3dbcbb10d9c988835a485/UnitTests/TestDetourNoTDx64.cpp#L102

It is weird that  if executing the single test case "Minimal ILCallback", it just works fine, but if running the whole test cases, it crashes (SIGSEG), the debug version also works fine.

After debugging the release version of binary, I found the memset() function is modified at runtime because of a code-cave-too-small issue.  Other parts of unit-tests have corrupted the code before the test section is executed.

ref: https://github.com/randydu/PolyHook_2_0/issues/2#issuecomment-828623027

**Comment by stevemk14ebr** [comment]
Hi, this is fixed here: https://github.com/stevemk14ebr/PolyHook_2_0/commit/b6981805314d849bd0d49a21daed8cb2daae8034
